// packages/sources/react/src/components/VtmnToggle/VtmnToggle.tsx
import * as React from 'react';
import clsx from 'clsx';

import '@vtmn/css-toggle/dist/index-with-vars.css';
import { VtmnToggleSize } from './types';

export interface VtmnToggleProps
  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> {
  /**
   * ID of the toggle.
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the toggle.
   * @type {string}
   */
  labelText: string;

  /**
   * The size of the toggle.
   * @default 'medium'
   */
  size?: VtmnToggleSize;

  /**
   * Label text linked to the toggle.
   * @type {boolean}
   * @default false
   */
  checked?: boolean;

  /**
   * Disabled state of the toggle.
   * @type {boolean}
   */
  disabled?: boolean;
}

export const VtmnToggle = ({
  className,
  identifier,
  labelText,
  size = 'medium',
  checked,
  disabled,
  ...props
}: VtmnToggleProps) => {
  return (
    <div
      className={clsx('vtmn-toggle', `vtmn-toggle_size--${size}`, className)}>
      <div className="vtmn-toggle_switch">
        <input
          type="checkbox"
          id={identifier}
          defaultChecked={checked}
          disabled={disabled}
          {...props}
        />
        <span aria-hidden="true"></span>
      </div>
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

export default React.memo(VtmnToggle);

// packages/sources/web-components/src/components/vtmn-toggle/vtmn-toggle.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';

@Component({
  tag: 'vtmn-toggle',
  styleUrl: 'vtmn-toggle.pcss',
})
export class VtmnToggle implements ComponentInterface {
  /**
   * The id of the toggle and its label.
   */
  @Prop() identifier!: string;

  /**
   * The text of the toggle.
   */
  @Prop({ attribute: 'labeltext' }) labelText: string;

  /**
   * The size of the toggle.
   */
  @Prop() size: 'small' | 'medium';

  /**
   * The checked state of the toggle.
   * @default false
   */
  @Prop() checked: boolean;

  /**
   * The disabled state of the toggle.
   * @default false
   */
  @Prop() disabled: boolean;

  render() {
    return (
      <div class={['vtmn-toggle', `vtmn-toggle_size--${this.size}`].join(' ')}>
        <div class="vtmn-toggle_switch">
          <input
            type="checkbox"
            id={this.identifier}
            checked={this.checked}
            disabled={this.disabled}
          />
          <span aria-hidden="true"></span>
        </div>
        <label htmlFor={this.identifier}>{this.labelText}</label>
      </div>
    );
  }
}
