// packages/sources/web-components/src/components/vtmn-loader/vtmn-loader.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';

@Component({
  tag: 'vtmn-loader',
  styleUrl: 'vtmn-loader.pcss',
})
export class VtmnLoader implements ComponentInterface {
  /**
   * The size of the loader.
   * @type {string}
   * @defaultValue 'medium'
   */
  @Prop() size: 'small' | 'medium' | 'large' = 'medium';

  render() {
    return (
      <div
        class={['vtmn-loader', `vtmn-loader_size--${this.size}`].join(' ')}
      ></div>
    );
  }
}

// packages/sources/svelte/src/components/indicators/VtmnLoader/VtmnLoader.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VTMN_LOADER_SIZE } from './enums';

  /**
   * The size of the loader.
   * @type {'small' | 'medium' | 'large'}
   */
  export let size = VTMN_LOADER_SIZE.MEDIUM;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-loader',
    size && `vtmn-loader_size--${size}`,
    className,
  );
</script>

<div class={componentClass} {...$$restProps} />

<style lang="css">
  @import '@vtmn/css-loader';
</style>
