// packages/sources/react/src/components/VtmnRadioButton/VtmnRadioButton.tsx
import * as React from 'react';

import '@vtmn/css-radio-button';

export interface VtmnRadioProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * ID of the radio.
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the radio.
   * @type {string}
   * @default undefined
   */
  labelText?: string;

  /**
   * Name of the radio.
   * @type {string}
   * @default undefined
   */
  name?: string;

  /**
   * Label text linked to the radio.
   * @type {string}
   * @default null
   */
  value?: string;

  /**
   * Label text linked to the radio.
   * @type {boolean}
   * @default false
   */
  checked?: boolean;

  /**
   * Disabled state of the radio.
   * @type {boolean}
   */
  disabled?: boolean;
}

export const VtmnRadioButton = ({
  identifier,
  labelText,
  name,
  value,
  checked,
  disabled,
  ...props
}: VtmnRadioProps) => {
  return (
    <div>
      <input
        className="vtmn-radio-button"
        type="radio"
        id={identifier}
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        {...props}
      />
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

export default React.memo(VtmnRadioButton);

// packages/sources/svelte/src/components/selection-controls/VtmnRadioButton/VtmnRadioButton.svelte
<script>
  /**
   * ID of input
   * @type {string}
   * @requires
   */
  export let id;

  /**
   * Name of input
   * @type {string} input name
   * @requires
   */
  export let name;

  /**
   * Label of input
   * @type {string}
   * @requires
   */
  export let label;

  /**
   * Whether the input is checked
   * @type {boolean}
   * @default false
   */
  export let checked = false;

  /**
   * Whether the input is disabled
   * @type {boolean}
   * @default false
   */
  export let disabled = false;
</script>

<div>
  <input
    class="vtmn-radio-button"
    type="radio"
    {id}
    {name}
    {checked}
    {disabled}
  />
  <label for={id}>{label}</label>
</div>

<style lang="css">
  @import '@vtmn/css-radio-button';
</style>
