// packages/sources/vue/src/components/structure/VtmnCard/VtmnCard.vue
<script lang="ts">
import '@vtmn/css-card/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnCardVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnCard',
  inheritAttrs: false,
  props: {
    title: {
      type: String as PropType<string>,
      default: 'Card title',
    },
    variant: {
      type: String as PropType<VtmnCardVariant>,
      default: 'top-image',
      validator: (val: VtmnCardVariant) =>
        ['top-image', 'side-image', 'full-image'].includes(val),
    },
    fullImage: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    contentOpaque: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    headingLevel: {
      type: Number as PropType<number>,
      default: 2,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      componentClasses: computed(() => ({
        'vtmn-card': true,
        [`vtmn-card_variant--${props.variant}`]: props.variant,
      })),

      componentImageClasses: computed(() => ({
        'vtmn-card_image': true,
        'vtmn-card_image--full':
          props.variant === 'top-image' && props.fullImage,
      })),

      componentContentClasses: computed(() => ({
        'vtmn-card_content': true,
        'vtmn-card_content--opaque':
          props.variant === 'full-image' && props.contentOpaque,
      })),

      Heading: computed(() => {
        return props.headingLevel >= 0 && props.headingLevel <= 6
          ? `h${props.headingLevel}`
          : 'h2';
      }),
    };
  },
});
</script>

<template>
  <div :class="componentClasses" v-bind="$attrs">
    <div v-if="$slots['img']" :class="componentImageClasses">
      <slot name="img" />
    </div>
    <div :class="componentContentClasses">
      <component
        :is="Heading"
        v-if="$props.title"
        class="vtmn-card_content--title"
      >
        {{ $props.title }}
      </component>

      <template v-if="$slots['content']">
        <span class="vtmn-card_content--body">
          <slot name="content" />
        </span>
      </template>

      <template v-if="$slots['actions']">
        <slot name="actions" />
      </template>
    </div>
  </div>
</template>

// packages/sources/react/src/components/structure/VtmnCard/VtmnCard.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-card/dist/index-with-vars.css';
import { VtmnCardVariant } from './types';

export interface VtmnCardProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The variant of the card
   * @defaultValue 'top-image'
   */
  variant?: VtmnCardVariant;

  /**
   * The title of the card
   */
  title: string;

  /**
   * The fullscreen property of the image
   * @defaultValue false
   */
  img?: React.ReactNode;

  /**
   * The fullscreen property of the image
   * @defaultValue false
   */
  fullImage?: boolean;

  /**
   * The opaque property of image,
   * only on card variant 'full-image'
   * @defaultValue false
   */
  contentOpaque?: boolean;

  /**
   * Heading level of the title
   * @defaultValue 2
   */
  headingLevel?: 1 | 2 | 3 | 4 | 5 | 6;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnCard = ({
  variant = 'top-image',
  title,
  img,
  fullImage = false,
  contentOpaque = false,
  headingLevel = 2,
  children,
  className,
}: VtmnCardProps) => {
  const Heading =
    headingLevel >= 0 && headingLevel <= 6
      ? (`h${headingLevel}` as keyof JSX.IntrinsicElements)
      : 'h2';

  return (
    <div className="vtmn-card-container">
      <div
        className={clsx(
          'vtmn-card',
          `vtmn-card_variant--${variant}`,
          className,
        )}
      >
        <div
          className={clsx('vtmn-card_image', {
            'vtmn-card_image--full': fullImage && variant === 'top-image',
          })}
        >
          {img && img}
        </div>
        <div
          className={clsx('vtmn-card_content', {
            'vtmn-card_content--opaque':
              contentOpaque && variant === 'full-image',
          })}
        >
          {title && (
            <Heading className="vtmn-card_content--title">{title}</Heading>
          )}
          {children && (
            <span className="vtmn-card_content--body">{children}</span>
          )}
        </div>
      </div>
    </div>
  );
};

const MemoVtmnCard = React.memo(VtmnCard);

MemoVtmnCard.displayName = 'VtmnCard';

export default MemoVtmnCard;
