// packages/sources/react/src/components/VtmnCheckbox/VtmnCheckbox.tsx
import * as React from 'react';

import '@vtmn/css-checkbox';

export interface VtmnCheckboxProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * ID of the checkbox.
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  labelText?: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  name?: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  value?: string;

  /**
   * Label text linked to the checkbox.
   * @type {boolean}
   * @default false
   */
  checked?: boolean;

  /**
   * Label text linked to the checkbox.
   * @type {boolean}
   * @default false
   */
  disabled?: boolean;
}

export const VtmnCheckbox = ({
  identifier,
  labelText,
  name,
  value,
  checked,
  disabled,
  ...props
}: VtmnCheckboxProps) => {
  return (
    <div>
      <input
        className="vtmn-checkbox"
        type="checkbox"
        id={identifier}
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        {...props}
      />
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

export default React.memo(VtmnCheckbox);

// packages/sources/web-components/src/components/vtmn-checkbox/vtmn-checkbox.tsx
import { Component, Prop, h, ComponentInterface, Host } from '@stencil/core';

@Component({
  tag: 'vtmn-checkbox',
  styleUrl: 'vtmn-checkbox.pcss',
})
export class VtmnCheckbox implements ComponentInterface {
  /**
   * The id of the checkbox and its label.
   */
  @Prop() identifier!: string;

  /**
   * The value of the checkbox.
   */
  @Prop() value: string;

  /**
   * The name of the checkbox.
   */
  @Prop() name: string;

  /**
   * The text of the checkbox.
   */
  @Prop({ attribute: 'labeltext' }) labelText: string;

  /**
   * The disabled state of the checkbox.
   * @default false
   */
  @Prop() disabled: boolean;

  /**
   * The checked state of the checkbox.
   * @default false
   */
  @Prop() checked: boolean;

  render() {
    return (
      <Host>
        <input
          class="vtmn-checkbox"
          type="checkbox"
          id={this.identifier}
          name={this.name}
          value={this.value}
          checked={this.checked}
          disabled={this.disabled}
        />
        <label htmlFor={this.identifier}>{this.labelText}</label>
      </Host>
    );
  }
}
