// packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
<script>
  import { cn } from '../../../utils/classnames';

  /**
   * @type {string} Summary of the accordion.
   * @requires
   */
  export let summary;

  /**
   * @type {boolean} Display left icon on summary.
   * @default false
   */
  export let withIconLeft = false;

  /**
   * @type {boolean} Disable the accordion.
   * @default false
   */
  export let disabled = false;

  /**
   * @type {boolean} Open the accordion.
   * @default false
   */
  export let open = false;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };
  $: componentClass = cn(
    'vtmn-accordion',
    withIconLeft && 'vtmn-accordion--with-icon-left',
    className,
  );
</script>

<details
  class={componentClass}
  aria-disabled={disabled}
  aria-expanded={open}
  {open}
  {...$$restProps}
>
  <summary>{summary}</summary>
  <div class="vtmn-accordion_content">
    <slot />
  </div>
</details>

<style lang="css">
  @import '@vtmn/css-accordion';
</style>

// packages/sources/react/src/components/structure/VtmnAccordion/VtmnAccordion.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-accordion';

export interface VtmnAccordionProps
  extends React.ComponentPropsWithoutRef<'details'> {
  /**
   * @type {string} Summary of the accordion.
   * @requires
   */
  summary?: string;

  /**
   * @type {boolean} Display left icon on summary.
   * @default false
   */
  withIconLeft?: boolean;

  /**
   * @type {boolean} Disable the accordion.
   * @default false
   */
  disabled?: boolean;

  /**
   * @type {boolean} Open the accordion.
   * @default false
   */
  open?: boolean;
}

export const VtmnAccordion = ({
  summary,
  withIconLeft,
  disabled,
  open,
  children,
  className,
  ...props
}: VtmnAccordionProps) => {
  return (
    <details
      className={clsx(
        'vtmn-accordion',
        withIconLeft && 'vtmn-accordion--with-icon-left',
        className,
      )}
      aria-disabled={disabled}
      aria-expanded={open}
      open={open}
      {...props}
    >
      <summary>{summary}</summary>
      <div className="vtmn-accordion_content">{children}</div>
    </details>
  );
};

const MemoVtmnAccordion = React.memo(VtmnAccordion);

MemoVtmnAccordion.displayName = 'VtmnAccordion';

export default MemoVtmnAccordion;
