// packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
<script lang="ts">
import '@vtmn/css-search/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnSearchVariant, VtmnSearchSize } from './types';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnSearch',
  components: { VtmnButton },
  props: {
    value: {
      type: String as PropType<string>,
      default: undefined,
    },
    variant: {
      type: String as PropType<VtmnSearchVariant>,
      default: 'medium',
    },
    placeholder: {
      type: String as PropType<string>,
      default: undefined,
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    size: {
      type: String as PropType<VtmnSearchSize>,
      default: 'medium',
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-search': true,
        [`vtmn-search_variant--${props.variant}`]: props.variant,
        [`vtmn-search_size--${props.size}`]: props.size,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes" role="search">
    <input
      type="search"
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
    />

    <div class="vtmn-search_buttons">
      <VtmnButton
        iconAlone="close-line"
        variant="ghost"
        :disabled="disabled"
        :size="size"
        aria-label="close"
        :aria-disabled="disabled"
      />

      <VtmnButton
        iconAlone="search-line"
        variant="ghost"
        :disabled="disabled"
        :size="size"
        type="submit"
        aria-label="search"
      />
    </div>
  </div>
</template>

// packages/sources/react/src/components/navigation/VtmnSearch/VtmnSearch.tsx
import * as React from 'react';
import '@vtmn/css-search/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnSearchVariant, VtmnSearchSize } from './types';
import { VtmnButton } from '../../actions/VtmnButton/VtmnButton';

export interface VtmnSearchProps
  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> {
  /**
   * The variant of the search bar.
   * @type {VtmnSearchVariant}
   * @defaultValue 'default'
   */
  variant?: VtmnSearchVariant;

  /**
   * The size of the search bar.
   * @type {VtmnSearchSize}
   * @defaultValue 'medium'
   */
  size?: VtmnSearchSize;

  /**
   * The disabled state of the search bar.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;

  /**
   * The placeholder of the search bar.
   * @type {string}
   * @defaultValue 'Search'
   */
  placeholder?: string;

  /**
   * The value of the search bar.
   * @type {string}
   * @defaultValue undefined
   */
  value?: string;
}

export const VtmnSearch = ({
  variant = 'default',
  size = 'medium',
  disabled = false,
  placeholder = 'Search',
  value = undefined,
  className,
  ...props
}: VtmnSearchProps) => {
  const [search, setSearch] = React.useState(value);

  return (
    <div
      className={clsx(
        'vtmn-search',
        `vtmn-search_variant--${variant}`,
        `vtmn-search_size--${size}`,
        className,
      )}
      role="search"
    >
      <input
        placeholder={placeholder}
        value={search}
        disabled={disabled}
        type="search"
        {...props}
        onChange={(event) => {
          // Overwrite previously defined onChange then call it back once search is set
          setSearch(event.target.value);
          props.onChange && props.onChange(event);
        }}
      />

      <div className="vtmn-search_buttons">
        {search && (
          <VtmnButton
            variant="ghost"
            size={size}
            disabled={disabled}
            iconAlone="close-line"
            onClick={() => setSearch('')}
            aria-label="close"
          />
        )}

        <VtmnButton
          variant="ghost"
          size={size}
          disabled={disabled}
          type="submit"
          iconAlone="search-line"
          aria-label="search"
        />
      </div>
    </div>
  );
};

const MemoVtmnSearch = React.memo(VtmnSearch);

MemoVtmnSearch.displayName = 'VtmnSearch';

export default MemoVtmnSearch;
