// packages/sources/vue/src/components/overlays/VtmnTooltip/VtmnTooltip.vue
<script lang="ts">
import '@vtmn/css-tooltip/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';
import { VtmnTooltipPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTooltip',
  inheritAttrs: false,
  props: {
    tooltip: {
      type: String as PropType<string>,
    },
    position: {
      type: String as PropType<VtmnTooltipPosition>,
      default: 'top',
      validator: (val: VtmnTooltipPosition) =>
        [
          'bottom-left',
          'bottom',
          'bottom-right',
          'left',
          'right',
          'top-left',
          'top',
          'top-right',
        ].includes(val),
    },
  },
});
</script>

<template>
  <span
    tabindex="0"
    class="vtmn-tooltip"
    :data-tooltip="tooltip"
    :data-position="position"
    role="tooltip"
    v-bind="$attrs"
  >
    <slot />
  </span>
</template>

// packages/sources/svelte/src/components/overlays/VtmnTooltip/VtmnTooltip.svelte
<script>
  import { VTMN_TOOLTIP_POSITION } from './enums';

  /**
   * @type {'bottom-left' | 'bottom' | 'bottom-right' | 'left' | 'right' | 'top-left' | 'top'| 'top-right' }  The tooltip position
   * @defaultValue top
   */
  export let position = VTMN_TOOLTIP_POSITION.TOP;

  /**
   * @type {string} The printed tooltip.
   */
  export let tooltip;
</script>

<span
  tabindex="0"
  class="vtmn-tooltip"
  data-tooltip={tooltip}
  data-position={position}
  role="tooltip"
>
  <slot />
</span>

<style lang="css">
  @import '@vtmn/css-tooltip';
</style>
