// packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
<script lang="ts">
import '@vtmn/css-search/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnSearchVariant, VtmnSearchSize } from './types';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnSearch',
  components: { VtmnButton },
  props: {
    value: {
      type: String as PropType<string>,
      default: undefined,
    },
    variant: {
      type: String as PropType<VtmnSearchVariant>,
      default: 'medium',
    },
    placeholder: {
      type: String as PropType<string>,
      default: undefined,
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    size: {
      type: String as PropType<VtmnSearchSize>,
      default: 'medium',
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-search': true,
        [`vtmn-search_variant--${props.variant}`]: props.variant,
        [`vtmn-search_size--${props.size}`]: props.size,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes" role="search">
    <input
      type="search"
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
    />

    <div class="vtmn-search_buttons">
      <VtmnButton
        iconAlone="close-line"
        variant="ghost"
        :disabled="disabled"
        :size="size"
        aria-label="close"
        :aria-disabled="disabled"
      />

      <VtmnButton
        iconAlone="search-line"
        variant="ghost"
        :disabled="disabled"
        :size="size"
        type="submit"
        aria-label="search"
      />
    </div>
  </div>
</template>

// packages/sources/svelte/src/components/navigation/VtmnSearch/VtmnSearch.svelte
<script>
  import { VtmnButton } from '@vtmn/svelte';
  import { createEventDispatcher } from 'svelte';

  /** @restProps { button } */

  /**
   * The variant of the button.
   * @type {'default' | 'ghost' | 'persistent' | 'on-content'}
   * @defaultValue 'default'
   */
  export let variant = 'default';

  /**
   * @type {boolean} disabled.
   * @defaultValue false
   */
  export let disabled = false;

  /**
   * @type {'small' | 'medium'}
   * @defaultValue 'medium'
   */
  export let size = 'medium';

  /**
   * The value of the input
   * @type {string}
   */
  export let value;

  const dispatch = createEventDispatcher();

  const resetInputValue = () => {
    value = '';
  };

  const onSearch = () => {
    dispatch('search', {
      text: value,
    });
  };
</script>

<form
  class={`vtmn-search vtmn-search_size--${size} vtmn-search_variant--${variant}`}
  action=""
  role="search"
  aria-controls="search-result"
  on:submit|preventDefault={onSearch}
>
  <input
    type="search"
    {...$$restProps}
    on:click
    on:mouseover
    on:mouseenter
    on:mouseout
    on:focus
    on:blur
    on:keydown
    on:keypress
    on:keyup
    bind:value
    {disabled}
  />

  <div class="vtmn-search_buttons">
    <VtmnButton
      iconAlone="close-line"
      variant="ghost"
      {disabled}
      {size}
      on:click={resetInputValue}
      aria-label="close"
      aria-disabled={disabled}
    />

    <VtmnButton
      iconAlone="search-line"
      variant="ghost"
      {disabled}
      {size}
      type="submit"
      aria-label="search"
    />
  </div>
</form>

<style lang="css">
  @import '@vtmn/css-search';
</style>
