// packages/sources/react/src/components/indicators/VtmnLoader/VtmnLoader.tsx
import * as React from 'react';
import '@vtmn/css-loader/dist/index-with-vars.css';
import { VtmnLoaderSize } from './types';
import { objectValuesToString } from '../../../utils/object';

export interface VtmnLoaderProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The size of the loader.
   * @defaultValue 'medium'
   */
  size?: VtmnLoaderSize;
}

export const VtmnLoader = ({
  size = 'medium',
  className,
  ...props
}: VtmnLoaderProps) => {
  return (
    <div
      className={`vtmn-loader vtmn-loader_size--${size} ${className}`}
      {...objectValuesToString(props)}
    ></div>
  );
};

const MemoVtmnLoader = React.memo(VtmnLoader);

MemoVtmnLoader.displayName = 'VtmnLoader';

export default MemoVtmnLoader;

// packages/sources/vue/src/components/indicators/VtmnLoader/VtmnLoader.vue
<script lang="ts">
import '@vtmn/css-loader/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnLoaderSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnLoader',
  props: {
    size: {
      type: String as PropType<VtmnLoaderSize>,
      default: 'medium',
      validator: (val: VtmnLoaderSize) =>
        ['small', 'medium', 'large'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-loader': true,
        [`vtmn-loader_size--${props.size}`]: true,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes"></div>
</template>
