// packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbar.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VtmnButton } from '../../..';

  /**
   * @type {string} text write into the snackbar
   */
  export let content;

  /**
   * @type {boolean} display the snackbar
   * Default false
   */
  export let show = false;

  /**
   * @type {number} timeout before the snackbar disappear
   * Default 5000
   */
  export let timeout = 5000;

  /**
   * @type {boolean} display close button
   * Default false
   */
  export let displayCloseButton = false;

  let className = '';
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  let timeoutId;
  const closeHandler = () => {
    timeoutId && clearTimeout(timeoutId);
    show = false;
  };

  $: componentClass = cn('vtmn-snackbar', 'show', className);
  $: {
    if (show && timeout) {
      timeoutId = setTimeout(() => {
        show = false;
      }, timeout);
    }
  }
</script>

{#if show}
  <div class={componentClass} role="status">
    <div class="vtmn-snackbar_content">
      {content}
    </div>
    <slot />
    {#if displayCloseButton}
      <VtmnButton
        on:click={closeHandler}
        aria-label="Close alert"
        variant="ghost-reversed"
        size="small"
        iconAlone="close-line"
      />
    {/if}
  </div>
{/if}

<style>
  @import '@vtmn/css-snackbar';
</style>

// packages/sources/react/src/components/overlays/VtmnSnackbar/VtmnSnackbar.tsx
import * as React from 'react';
import '@vtmn/css-snackbar';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton';

export interface VtmnSnackbarProps
  extends Omit<React.ComponentPropsWithoutRef<'dialog'>, 'onClose'> {
  /**
   * The snackbaOmit<React.ComponentPropsWithoutRef<'dialog'>, 'onClose'>r's content
   */
  content: string;

  /**
   * The label of the action button
   */
  actionLabel?: string;

  /**
   * Whether there is a close button
   */
  withCloseButton?: boolean;

  /**
   * The alert callback close function
   * @type {function}
   */
  onClose?: (event: React.MouseEvent | undefined) => void;
}

export const VtmnSnackbar = ({
  content = '',
  actionLabel = 'Action',
  withCloseButton = false,
  onClose,
  className,
}: VtmnSnackbarProps) => {
  return (
    <div
      role="status"
      className={clsx('vtmn-snackbar', 'show', className)}
      onClick={onClose}
    >
      <div className="vtmn-snackbar_content">{content}</div>
      {onClose && actionLabel && (
        <VtmnButton size="small" variant="ghost-reversed" onClick={onClose}>
          {actionLabel}
        </VtmnButton>
      )}
      {onClose && withCloseButton && (
        <VtmnButton
          size="small"
          variant="ghost-reversed"
          iconAlone="close-line"
          aria-label="Close snackbar"
          onClick={onClose}
        ></VtmnButton>
      )}
    </div>
  );
};

const MemoVtmnSnackbar = React.memo(VtmnSnackbar);

MemoVtmnSnackbar.displayName = 'VtmnSnackbar';

export default MemoVtmnSnackbar;
