// packages/sources/vue/src/components/overlays/VtmnSnackbar/VtmnSnackbar.vue
<script lang="ts">
import '@vtmn/css-snackbar/dist/index-with-vars.css';
import { computed, defineComponent, PropType } from 'vue';
import { VtmnButton } from '../../index';

const INFINITE_TIMEOUT_MS = 9999000;

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnSnackbar',
  inheritAttrs: false,
  components: { VtmnButton },
  props: {
    withCloseButton: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    timeout: {
      type: Number as PropType<number>,
      default: 4500,
    },
    actionLabel: {
      type: String as PropType<string>,
      default: undefined,
    },
  },
  emits: ['close', 'action'],
  setup(props, { emit }) {
    const handleClose = (event: Event) => {
      return emit('close', (event.target as HTMLInputElement).value);
    };

    const handleAction = (event: Event) => {
      return emit('action', (event.target as HTMLInputElement).value);
    };

    return {
      classes: computed(() => ({
        'vtmn-snackbar': true,
        'show animate-delay': props.timeout > 0,
      })),
      style: {
        '--vtmn-animation_overlay-duration': `${
          typeof props.timeout === 'number' && props.timeout < Infinity
            ? props.timeout
            : INFINITE_TIMEOUT_MS
        }ms`,
      },
      handleClose,
      handleAction,
    };
  },
});
</script>

<template>
  <div :class="classes" :style="style" role="status" v-bind="$attrs">
    <div v-if="$slots.content" class="vtmn-snackbar_content">
      <slot name="content" />
    </div>
    <VtmnButton
      v-if="actionLabel"
      variant="ghost-reversed"
      size="small"
      :aria-label="actionLabel"
      @click="handleAction"
      >{{ actionLabel }}</VtmnButton
    >
    <VtmnButton
      v-if="withCloseButton"
      iconAlone="close-line"
      variant="ghost-reversed"
      size="small"
      aria-label="close"
      @click="handleClose"
    />
  </div>
</template>

// packages/sources/react/src/components/overlays/VtmnSnackbar/VtmnSnackbar.tsx
import * as React from 'react';
import '@vtmn/css-snackbar/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton';

const INFINITE_TIMEOUT_MS = 9999000;

export interface VtmnSnackbarProps
  extends Omit<React.ComponentPropsWithoutRef<'dialog'>, 'onClose'> {
  /**
   * The snackbaOmit<React.ComponentPropsWithoutRef<'dialog'>, 'onClose'>r's content
   */
  content: string;

  /**
   * The label of the action button
   */
  actionLabel?: string;

  /**
   * Whether there is a close button
   */
  withCloseButton?: boolean;

  /**
   * Duration of the snackbar in ms
   */
  timeout?: number;

  /**
   * The alert callback close function
   * @type {function}
   */
  onClose?: (event: React.MouseEvent | undefined) => void;
}

export const VtmnSnackbar = ({
  content = '',
  actionLabel = 'Action',
  withCloseButton = false,
  onClose,
  className,
  timeout = 4500,
}: VtmnSnackbarProps) => {
  const propertyStyle: Record<string, string> = {
    '--vtmn-animation_overlay-duration': `${
      timeout < Infinity ? timeout : INFINITE_TIMEOUT_MS
    }ms`,
  };
  return (
    <div
      role="status"
      style={propertyStyle}
      className={clsx(
        'vtmn-snackbar',
        timeout > 0 && 'show animate-delay',
        className,
      )}
      onClick={onClose}
    >
      <div className="vtmn-snackbar_content">{content}</div>
      {onClose && actionLabel && (
        <VtmnButton size="small" variant="ghost-reversed" onClick={onClose}>
          {actionLabel}
        </VtmnButton>
      )}
      {onClose && withCloseButton && (
        <VtmnButton
          size="small"
          variant="ghost-reversed"
          iconAlone="close-line"
          aria-label="Close snackbar"
          onClick={onClose}
        ></VtmnButton>
      )}
    </div>
  );
};

const MemoVtmnSnackbar = React.memo(VtmnSnackbar);

MemoVtmnSnackbar.displayName = 'VtmnSnackbar';

export default MemoVtmnSnackbar;
