// packages/sources/vue/src/components/VtmnToggle/VtmnToggle.vue
<script lang="ts">
import '@vtmn/css-toggle/dist/index-with-vars.css';
import { computed, defineComponent, reactive } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnToggle',
  props: {
    identifier: {
      type: String,
      default: null,
    },
    labelText: {
      type: String,
      default: null,
    },
    checked: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    size: {
      type: String,
      default: null,
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-toggle': true,
        [`vtmn-toggle_size--${props.size}`]: props.size,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes">
    <div class="vtmn-toggle_switch">
      <input
        type="checkbox"
        :id="this.identifier"
        :checked="this.checked"
        :disabled="this.disabled"
      />
      <span aria-hidden="true"></span>
    </div>
    <label :for="this.identifier">{{ this.labelText }}</label>
  </div>
</template>

// packages/sources/react/src/components/selection-controls/VtmnToggle/VtmnToggle.tsx
import * as React from 'react';
import '@vtmn/css-toggle/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnToggleSize } from './types';

export interface VtmnToggleProps
  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> {
  /**
   * The id of the toggle.
   * @type {string}
   */
  identifier: string;

  /**
   * The label of the toggle.
   * @type {string}
   * @defaultValue undefined
   */
  labelText?: string;

  /**
   * The size of the toggle.
   * @defaultValue 'medium'
   */
  size?: VtmnToggleSize;

  /**
   * The checked state of the toggle.
   * @type {boolean}
   * @defaultValue false
   */
  checked?: boolean;

  /**
   * The disabled state of the toggle.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;
}

export const VtmnToggle = ({
  className,
  identifier,
  labelText,
  size = 'medium',
  checked = false,
  disabled = false,
  ...props
}: VtmnToggleProps) => {
  return (
    <div
      className={clsx('vtmn-toggle', `vtmn-toggle_size--${size}`, className)}
    >
      <div className="vtmn-toggle_switch">
        <input
          type="checkbox"
          id={identifier}
          checked={checked}
          disabled={disabled}
          {...props}
        />
        <span aria-hidden="true"></span>
      </div>
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

const MemoVtmnToggle = React.memo(VtmnToggle);

MemoVtmnToggle.displayName = 'VtmnToggle';

export default MemoVtmnToggle;
