// packages/sources/vue/src/components/selection-controls/VtmnToggle/VtmnToggle.vue
<script lang="ts">
import '@vtmn/css-toggle/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnToggleSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnToggle',
  props: {
    modelValue: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    identifier: {
      type: String as PropType<string>,
      default: null,
    },
    labelText: {
      type: String as PropType<string>,
      default: null,
    },
    checked: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    size: {
      type: String as PropType<VtmnToggleSize>,
      default: 'medium',
    },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    props = reactive(props);

    const handleChange = (event: Event) => {
      if (event && event.target) {
        return emit(
          'update:modelValue',
          (event.target as HTMLInputElement).checked,
        );
      }
    };

    return {
      classes: computed(() => ({
        'vtmn-toggle': true,
        [`vtmn-toggle_size--${props.size}`]: props.size,
      })),
      handleChange,
    };
  },
});
</script>

<template>
  <div :class="classes">
    <div class="vtmn-toggle_switch">
      <input
        type="checkbox"
        :id="identifier"
        :checked="checked"
        :disabled="disabled"
        @change="handleChange"
      />
      <span aria-hidden="true"></span>
    </div>
    <label :for="identifier">{{ labelText }}</label>
  </div>
</template>

// packages/sources/react/src/components/selection-controls/VtmnToggle/VtmnToggle.tsx
import * as React from 'react';
import '@vtmn/css-toggle/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnToggleSize } from './types';

export interface VtmnToggleProps
  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> {
  /**
   * The id of the toggle.
   * @type {string}
   */
  identifier: string;

  /**
   * The label of the toggle.
   * @type {string}
   * @defaultValue undefined
   */
  labelText?: string;

  /**
   * The size of the toggle.
   * @defaultValue 'medium'
   */
  size?: VtmnToggleSize;

  /**
   * The checked state of the toggle.
   * @type {boolean}
   * @defaultValue false
   */
  checked?: boolean;

  /**
   * The disabled state of the toggle.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;
}

export const VtmnToggle = React.forwardRef<HTMLInputElement, VtmnToggleProps>(
  (
    {
      className,
      identifier,
      labelText,
      size = 'medium',
      checked = false,
      disabled = false,
      ...props
    },
    ref,
  ) => {
    return (
      <div
        className={clsx('vtmn-toggle', `vtmn-toggle_size--${size}`, className)}
      >
        <div className="vtmn-toggle_switch">
          <input
            type="checkbox"
            id={identifier}
            checked={checked}
            disabled={disabled}
            ref={ref}
            {...props}
          />
          <span aria-hidden="true"></span>
        </div>
        <label htmlFor={identifier}>{labelText}</label>
      </div>
    );
  },
);

const MemoVtmnToggle = React.memo(VtmnToggle);

MemoVtmnToggle.displayName = 'VtmnToggle';

export default MemoVtmnToggle;
