// packages/sources/vue/src/components/navigation/VtmnTabsItem/VtmnTabsItem.vue
<script lang="ts">
import '@vtmn/css-tabs/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';
import VtmnBadge from '../../indicators/VtmnBadge/VtmnBadge.vue';
import { defineComponent, PropType } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTabs',
  components: { VtmnBadge, VtmnIcon },
  props: {
    href: {
      type: String as PropType<string>,
      default: '#',
    },
    icon: {
      type: String as PropType<VitamixId>,
      default: undefined,
    },
    badgeValue: {
      type: Number as PropType<number>,
      default: undefined,
    },
  },
  setup() {
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
    };
  },
});
</script>

<template>
  <li role="tab">
    <a :href="href" v-bind="$attrs">
      <VtmnIcon
        v-if="icon"
        :value="icon"
        :style="styleObject"
        aria-hidden="true"
      />
      <slot />
      <VtmnBadge v-if="badgeValue" :value="badgeValue" />
    </a>
  </li>
</template>

// packages/sources/svelte/src/components/navigation/VtmnTabsItem/VtmnTabsItem.svelte
<script>
  import VtmnBadge from '../../indicators/VtmnBadge/VtmnBadge.svelte';
  import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.svelte';
  export let href = '#';
  export let badgeValue = undefined;
  export let icon = undefined;
</script>

<li role="tab">
  <a
    {...$$restProps}
    {href}
    on:click|preventDefault
    on:mouseover
    on:mouseenter
    on:mouseout
    on:focus
    on:blur
    on:keydown
  >
    {#if icon}
      <VtmnIcon value={icon} aria-hidden="true" />
    {/if}
    <slot />
    {#if badgeValue}
      <VtmnBadge value={badgeValue} />
    {/if}
  </a>
</li>
