// packages/sources/react/src/components/VtmnTooltip/VtmnTooltip.tsx
import * as React from 'react';
import '@vtmn/css-tooltip/dist/index-with-vars.css';
import { VtmnTooltipPosition } from './types';

export interface VtmnTooltipProps
  extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * The position of tooltip from original element.
   * @defaultValue 'top'
   */
  position?: VtmnTooltipPosition;

  /**
   * The tooltip text of the span.
   * @defaultValue undefined
   */
  tooltip: string;

  /**
   * The tooltip children
   * @defaultValue undefined
   */
  children: React.ReactNode;
}

export const VtmnTooltip = ({
  children,
  position = 'top',
  tooltip,
  className,
  ...props
}: VtmnTooltipProps) => {
  return (
    <div className="vtmn-flex">
      <span
        tabIndex={0}
        className={`vtmn-tooltip ${className ?? className}`}
        data-tooltip={tooltip}
        data-position={position}
        {...props}
      >
        {children}
      </span>
    </div>
  );
};

const MemoVtmnTooltip = React.memo(VtmnTooltip);

MemoVtmnTooltip.displayName = 'VtmnTooltip';

export default MemoVtmnTooltip;

// packages/sources/vue/src/components/overlays/VtmnTooltip/VtmnTooltip.vue
<script lang="ts">
import '@vtmn/css-tooltip/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';
import { VtmnTooltipPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTooltip',
  inheritAttrs: false,
  props: {
    tooltip: {
      type: String as PropType<string>,
    },
    position: {
      type: String as PropType<VtmnTooltipPosition>,
      default: 'top',
      validator: (val: VtmnTooltipPosition) =>
        [
          'bottom-left',
          'bottom',
          'bottom-right',
          'left',
          'right',
          'top-left',
          'top',
          'top-right',
        ].includes(val),
    },
  },
});
</script>

<template>
  <span
    tabindex="0"
    class="vtmn-tooltip"
    :data-tooltip="tooltip"
    :data-position="position"
    role="tooltip"
    v-bind="$attrs"
  >
    <slot />
  </span>
</template>
