// packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx
import clsx from 'clsx';
import '@vtmn/css-rating';
import * as React from 'react';
import { VtmnRatingSize } from './types';

export interface VtmnRatingProps
  extends Omit<React.ComponentPropsWithoutRef<'div'>, 'onChange'> {
  /**
   * The name of the input.
   * @type {string}
   * @defaultValue rating
   */
  name?: string;

  /**
   * The emphasis of the rating.
   * @type {boolean}
   * @defaultValue false
   */
  emphasis?: boolean;

  /**
   * The size of the rating.
   * @type {VtmnRatingSize}
   * @defaultValue medium
   */
  size?: VtmnRatingSize;

  /**
   * The disabled state of the rating.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;

  /**
   * Is the rating read only.
   * @type {boolean}
   * @defaultValue false
   */
  readonly?: boolean;

  /**
   * Is the rating should be displayed as compact.
   * @type {boolean}
   * @defaultValue false
   */
  compact?: boolean;

  /**
   * Comments next to the rating when using compact mode.
   * @type {number}
   * @defaultValue 0
   */
  comments?: number;

  /**
   * The value of the rating.
   * @type {number}
   * @defaultValue 0
   */
  value?: number;

  /**
   * Whether the value is shown next to the rating (requires readonly to be true)
   */
  showValue?: boolean;

  /**
   * Called when the rating value changes
   * @type {void}
   * @defaultValue undefined
   */
  onChange?: (newRating: number) => void;
}

export const VtmnRating = ({
  name = 'rating',
  emphasis = undefined,
  size = 'medium',
  disabled = false,
  readonly = false,
  compact = false,
  comments = undefined,
  value = 0,
  showValue = false,
  onChange = undefined,
  className,
  ...props
}: VtmnRatingProps) => {
  const [position, setPosition] = React.useState(value);

  // Update rating when value prop changes
  React.useEffect(() => setPosition(value), [value]);

  React.useEffect(() => onChange && onChange(position), [position]);

  return (
    <div
      className={clsx(
        'vtmn-rating',
        emphasis && 'vtmn-rating_variant--brand',
        `vtmn-rating_size--${size}`,
        className,
      )}
      aria-disabled={disabled}
      {...props}
    >
      {/**
       * Interactive mode
       */}
      {!readonly && (
        <div
          className="vtmn-rating--interactive"
          aria-label="Rate the article"
          role="radiogroup"
          data-rating={position}
        >
          {Array.from(Array(5).keys()).map((index) => (
            <React.Fragment key={`rating-${index + 1}`}>
              <input
                onChange={(event: React.FormEvent<HTMLInputElement>) =>
                  setPosition(parseInt(event.currentTarget.value))
                }
                type="radio"
                name={name}
                id={`${name}-${index + 1}`}
                value={index + 1}
                aria-label={`${index + 1} star out of 5`}
                disabled={disabled}
                checked={Math.floor(position) == index + 1}
              />
              <label htmlFor={`${name}-${index + 1}`} />
            </React.Fragment>
          ))}
        </div>
      )}

      {/**
       * Read-Only mode
       */}
      {readonly && (
        <React.Fragment>
          {/**
           * Compact rendering
           */}

          {compact ? (
            <span
              className={`vtmx-star-${!position ? 'line' : 'fill'}`}
              role="presentation"
            />
          ) : (
            Array.from(Array(5).keys()).map((index) => (
              <span
                key={`rating-readonly-${index + 1}`}
                className={
                  index <= position && position - index >= 0.5
                    ? position - index < 1 && position - index >= 0.5
                      ? 'vtmx-star-half-fill'
                      : 'vtmx-star-fill'
                    : 'vtmx-star-line'
                }
                role="presentation"
              />
            ))
          )}

          {/**
           * Value rendering
           */}
          {showValue && (
            <span
              className="vtmn-rating_comment--primary"
              aria-label="article rating"
            >
              {position}/5
            </span>
          )}

          {/**
           * Comments rendering
           */}
          {comments && (
            <span
              className="vtmn-rating_comment--secondary"
              aria-label="number of ratings"
            >
              {comments}
            </span>
          )}
        </React.Fragment>
      )}
    </div>
  );
};

const MemoVtmnRating = React.memo(VtmnRating);

MemoVtmnRating.displayName = 'VtmnRating';

export default MemoVtmnRating;

// packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { isFloat } from '../../../utils/math';
  import { VTMN_RATING_SIZE } from './enum';
  import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.svelte';

  /**
   * @type {string} name used on interactive mode to name the inputs
   * @required
   */
  export let name;

  /**
   * @type {boolean} use the emphasis mode. Only if readonly is true.
   * @default false
   */
  export let emphasis = false;

  /**
   * @type {boolean} size of the component
   * @default medium
   */
  export let size = VTMN_RATING_SIZE.MEDIUM;

  /**
   * @type {boolean} disable the component
   * @default false
   */
  export let disabled = false;

  /**
   * @type {boolean} is readonly component
   * @default false
   */
  export let readonly = false;

  /**
   * @type {boolean} enable the compact mode. Only if readonly is true.
   * @default false
   */
  export let compact = false;

  /**
   * @type {number} rating to display on the component
   * @requires
   */
  export let value;

  /**
   * @type {boolean} display the rating value. Only if readonly is true.
   * default false
   */
  export let showValue = false;

  /**
   * @type {number} Comments displayed after the rating. Only if readonly is true.
   */
  export let comments = undefined;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-rating',
    size && `vtmn-rating_size--${size}`,
    emphasis && 'vtmn-rating_variant--brand',
    className,
  );
  $: starsCnt = compact && readonly ? 1 : 5;

  const computeRatingFill = (currentRatingStar) => {
    if (starsCnt === 1) {
      return value === 0 ? 'line' : 'fill';
    }
    if (currentRatingStar <= value) {
      return 'fill';
    }
    if (
      value < currentRatingStar &&
      isFloat(value) &&
      Math.ceil(value) === currentRatingStar
    ) {
      return 'half-fill';
    }
    return 'line';
  };
</script>

<div class={componentClass} aria-disabled={disabled} {...$$restProps}>
  {#if !readonly}
    <div
      class="vtmn-rating--interactive"
      aria-label="Rate the article"
      role="radiogroup"
      data-rating={value}
    >
      {#each Array(starsCnt) as _, index}
        {@const position = index + 1}
        <input
          type="radio"
          bind:group={value}
          {name}
          value={position}
          id={`${name}-${position}`}
          aria-label={`${position} star out of 5`}
          {disabled}
        />
        <label for={`${name}-${position}`} />
      {/each}
    </div>
  {/if}
  {#if readonly}
    {#each Array(starsCnt) as _, index}
      {@const position = index + 1}
      <VtmnIcon
        value={`star-${computeRatingFill(position)}`}
        role="presentation"
      />
    {/each}
    {#if showValue}
      <span class="vtmn-rating_comment--primary" aria-label="article rating">
        {value}/5
      </span>
    {/if}
    {#if comments}
      <span
        class="vtmn-rating_comment--secondary"
        aria-label="number of ratings"
      >
        {comments}
      </span>
    {/if}
  {/if}
</div>

<style>
  @import '@vtmn/css-rating';
</style>
