// packages/sources/react/src/components/structure/VtmnSkeleton/VtmnSkeleton.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-skeleton';
import { VtmnSkeletonShape } from './types';

export interface VtmnSkeletonProps
  extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * Width of the skeleton (in percentage)..
   * @defaultValue 100
   */
  width?: number;

  /**
   * Define the type of shape.
   * @defaultValue 'line'
   */
  shape?: VtmnSkeletonShape;
}

export const VtmnSkeleton = ({
  width = 100,
  shape = 'line',
  className,
  ...props
}: VtmnSkeletonProps) => {
  return (
    <span
      className={clsx('vtmn-skeleton', `vtmn-skeleton_${shape}`, className)}
      style={{ width: `${width}%` }}
      {...props}
    ></span>
  );
};

const MemoVtmnSkeleton = React.memo(VtmnSkeleton);

MemoVtmnSkeleton.displayName = 'VtmnSkeleton';

export default MemoVtmnSkeleton;

// packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VTMN_SKELETON_SHAPE } from './enums';
  import { objectToStyle } from '../../../utils/style';

  /**
   * @type {number} width to apply to the skeleton (in percentage).
   * @defaultValue 100
   */
  export let width = 100;

  /**
   * @type {'line' | 'avatar' }  variant of the shape.
   * @defaultValue line
   */
  export let shape = VTMN_SKELETON_SHAPE.LINE;

  /**
   * @type {string} Custom classes to apply to the component.
   */
  let className = undefined;

  export { className as class };
  $: componentClass = cn(
    'vtmn-skeleton',
    shape && `vtmn-skeleton_${shape}`,
    width && `skeleton-width`,
    className,
  );

  $: componentStyle = objectToStyle({
    '--skeleton-width': `${width}%`,
  });
</script>

<span class={componentClass} style={componentStyle} />

<style lang="css">
  @import '@vtmn/css-skeleton';
  .skeleton-width {
    width: var(--skeleton-width, 0);
  }
</style>
