// packages/sources/react/src/components/overlays/VtmnAlert/VtmnAlert.tsx
import * as React from 'react';
import '@vtmn/css-alert/dist/index-with-vars.css';
import { VtmnAlertVariant } from './types';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton';

export interface VtmnAlertProps
  extends Omit<React.ComponentPropsWithoutRef<'dialog'>, 'onClose'> {
  /**
   * The alert's title
   */
  title: string;

  /**
   * The alert's message
   */
  message?: string;

  /**
   * The alert's variant
   */
  variant: VtmnAlertVariant;

  /**
   * The alert callback close function
   * @type {function}
   */
  onClose?: (event: React.MouseEvent | undefined) => void;
}

export const VtmnAlert = ({
  variant = 'info',
  title,
  message,
  onClose,
  className,
}: VtmnAlertProps) => {
  return (
    <div
      aria-label={title}
      role="dialog"
      className={clsx(
        'vtmn-alert',
        `vtmn-alert_variant--${variant}`,
        'show',
        className,
      )}
    >
      <article className="vtmn-alert_content">
        <div className="vtmn-alert_content-title">
          {title}
          {onClose && (
            <VtmnButton
              size="small"
              variant="ghost-reversed"
              iconAlone="close-line"
              aria-label="Close toast"
              onClick={onClose}
            ></VtmnButton>
          )}
        </div>
        {message && (
          <span className="vtmn-alert_content-description">{message}</span>
        )}
      </article>
    </div>
  );
};

const MemoVtmnAlert = React.memo(VtmnAlert);

MemoVtmnAlert.displayName = 'VtmnAlert';

export default MemoVtmnAlert;

// packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue
<script lang="ts">
import '@vtmn/css-alert/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnAlertVariant } from './types';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnAlert',
  components: { VtmnButton },
  inheritAttrs: false,
  props: {
    variant: {
      type: String as PropType<VtmnAlertVariant>,
      default: 'info',
      validator: (val: VtmnAlertVariant) =>
        ['info', 'success', 'warning', 'danger'].includes(val),
    },
    title: {
      type: String as PropType<string>,
      required: true,
    },
    message: {
      type: String as PropType<string>,
    },
    withCloseButton: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    ariaLabelCloseButton: {
      type: String as PropType<string>,
    },
    timeout: {
      type: Number as PropType<number>,
      default: 8000,
    },
    closeCallback: {
      type: Function as PropType<Function>,
      required: true,
    },
  },

  setup(props) {
    props = reactive(props);

    const handleClose = () => {
      return props.closeCallback();
    };
    return {
      classes: computed(() => ({
        'vtmn-alert': true,
        show: props.timeout > 0,
        [`vtmn-alert_variant--${props.variant}`]: props.variant,
      })),
      handleClose,
    };
  },
});
</script>

<template>
  <div :class="classes" role="alert" tabindex="-1" v-bind="$attrs">
    <div class="vtmn-alert_content" role="document">
      <div class="vtmn-alert_content-title">
        {{ title }}
        <VtmnButton
          v-if="withCloseButton"
          iconAlone="close-line"
          variant="ghost-reversed"
          size="small"
          :aria-label="ariaLabelCloseButton"
          @click.prevent="handleClose"
        />
      </div>
      <p v-if="message" class="vtmn-alert_content-description">
        {{ message }}
      </p>
    </div>
  </div>
</template>
