// packages/sources/react/src/components/structure/VtmnDivider/VtmnDivider.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-divider/dist/index-with-vars.css';
import { VtmnDividerOrientation, VtmnDividerTextPosition } from './types';

export interface VtmnDividerProps
  extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The orientation of the divider.
   * @defaultValue 'horizontal'
   */
  orientation?: VtmnDividerOrientation;

  /**
   * The position of the text inside the divider.
   * @defaultValue 'start'
   */
  textPosition?: VtmnDividerTextPosition;

  /**
   * The position of the text inside the divider.
   * @defaultValue undefined
   */
  ariaLabelId?: string;
}

export const VtmnDivider = ({
  orientation = 'horizontal',
  textPosition = 'start',
  ariaLabelId = undefined,
  children,
  className,
  ...props
}: VtmnDividerProps) => {
  return (
    <div
      className={clsx(
        'vtmn-divider',
        `vtmn-divider_orientation--${orientation}`,
        children && `vtmn-divider_text-position--${textPosition}`,
        className,
      )}
      {...props}
      role="separator"
      aria-orientation={orientation}
    >
      <span id={String(props['aria-labelledby'])}>{children}</span>
    </div>
  );
};

const MemoVtmnDivider = React.memo(VtmnDivider);

MemoVtmnDivider.displayName = 'VtmnDivider';

export default MemoVtmnDivider;

// packages/sources/vue/src/components/structure/VtmnDivider/VtmnDivider.vue
<script lang="ts">
import '@vtmn/css-divider/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnDividerOrientation, VtmnDividerTextPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnDivider',
  inheritAttrs: false,
  props: {
    orientation: {
      type: String as PropType<VtmnDividerOrientation>,
      default: 'horizontal',
      validator: (val: VtmnDividerOrientation) =>
        ['horizontal', 'vertical'].includes(val),
    },
    textPosition: {
      type: String as PropType<VtmnDividerTextPosition>,
      default: 'start',
      validator: (val: VtmnDividerTextPosition) =>
        ['start', 'center', 'end'].includes(val),
    },
    ariaLabelId: {
      type: String as PropType<string>,
      default: undefined,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'vtmn-divider': true,
        [`vtmn-divider_orientation--${props.orientation}`]: props.orientation,
        [`vtmn-divider_text-position--${props.textPosition}`]:
          props.textPosition,
      })),
    };
  },
});
</script>

<template>
  <div
    :class="classes"
    v-bind="$attrs"
    role="separator"
    :aria-orientation="orientation"
    :aria-labelledby="ariaLabelId"
  >
    <span :id="ariaLabelId"><slot /></span>
  </div>
</template>
