// packages/sources/vue/src/components/structure/VtmnListItem/VtmnListItem.vue
<script lang="ts">
import '@vtmn/css-list/dist/index-with-vars.css';
import { defineComponent, reactive, computed, PropType } from 'vue';
import { VtmnListItemSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnListItem',
  props: {
    size: {
      type: String as PropType<VtmnListItemSize>,
      default: 'medium',
      validator: (val: VtmnListItemSize) => ['small', 'medium'].includes(val),
    },
    divider: {
      type: Boolean as PropType<boolean>,
      default: true,
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        [`vtmn-list_item-size--${props.size}`]: true,
        ['vtmn-list_item--without-divider']: !props.divider,
      })),
    };
  },
});
</script>

<template>
  <li
    :class="classes"
    role="option"
    tabindex="0"
    :aria-disabled="disabled"
    v-bind="$attrs"
  >
    <div v-if="$slots['start-visual']" class="vtmn-list_start-visual">
      <slot name="start-visual" />
    </div>

    <div v-if="$slots['text']" class="vtmn-list_text">
      <slot name="text" />
      <template v-if="$slots['subtext']">
        <slot name="subtext" />
      </template>
    </div>

    <div v-if="$slots['end-action']" class="vtmn-list_end-action">
      <slot name="end-action" />
    </div>
  </li>
</template>

// packages/sources/svelte/src/components/structure/VtmnListItem/VtmnListItem.svelte
<script>
  /** @restProps */

  const SLOTS = $$props.$$slots;

  /**
   * The size of the list.
   *
   * @type {'small' | 'medium'} [medium]
   * @defaultValue 'medium'
   */
  export let size = 'medium';

  /**
   * Has divider.
   *
   * @type {boolean} [divider]
   * @defaultValue true
   */
  export let divider = true;

  /**
   * Index of item in list.
   *
   * @type {number} item
   */
  export let index;

  /**
   * Set disabled state of list item.
   *
   * @type {boolean} [disabled]
   * @defaultValue false
   */
  export let disabled = false;

  /**
   * Delete slot div from de DOM if slot doesn't exist.
   *
   * @param {'start-visual' | 'text' | 'subtext' | 'end-action'} slotName
   * @returns {boolean} slotExists
   */
  const checkSlotExists = (slotName) => {
    return SLOTS && SLOTS[slotName] && SLOTS[slotName].length;
  };
</script>

<li
  on:click
  class={`vtmn-list_item-size--${size}`}
  class:vtmn-list_item--without-divider={!divider}
  role="option"
  tabindex={index}
  aria-disabled={disabled}
  {...$$restProps}
>
  {#if checkSlotExists('start-visual')}
    <div class="vtmn-list_start-visual">
      <slot name="start-visual" />
    </div>
  {/if}

  {#if checkSlotExists('text')}
    <div class="vtmn-list_text">
      <slot name="text" />

      {#if checkSlotExists('subtext')}
        <slot name="subtext" />
      {/if}
    </div>
  {/if}

  {#if checkSlotExists('end-action')}
    <div class="vtmn-list_end-action">
      <slot name="end-action" />
    </div>
  {/if}
</li>
