// packages/sources/svelte/src/components/selection-controls/VtmnChip/VtmnChip.svelte
<script>
  import VtmnBadge from '../../indicators/VtmnBadge/VtmnBadge.svelte';
  import VtmnButton from '../../actions/VtmnButton/VtmnButton.svelte';
  import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.svelte';
  import { createEventDispatcher } from 'svelte';
  import { VTMN_CHIP_VARIANT, VTMN_CHIP_SIZE } from './enums';
  import { cn } from '../../../utils/classnames';

  const dispatch = createEventDispatcher();

  /**
   * The variant of the chip.
   */
  export let variant = VTMN_CHIP_VARIANT.SINGLE_CHOICE;

  /**
   * The size of the chip.
   */
  export let size = VTMN_CHIP_SIZE.MEDIUM;

  /**
   * The disabled state of the chip
   */
  export let disabled = false;

  /**
   * The selected state of the chip
   */
  export let selected = false;

  /**
   * The icon to display on the left side of the chip.
   * Only for 'input' variant
   */
  export let icon = undefined;

  /**
   * The value in the badge.
   * Only for `filter` variant
   */
  export let badgeValue = 0;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: isSelected =
    selected &&
    [VTMN_CHIP_VARIANT.SINGLE_CHOICE, VTMN_CHIP_VARIANT.FILTER].includes(
      variant,
    );
  $: componentClass = cn(
    'vtmn-chip',
    `vtmn-chip_variant--${variant}`,
    `vtmn-chip_size--${size}`,
    isSelected && 'vtmn-chip--selected',
    disabled ? 'vtmn-chip--disabled' : '',
    className,
  );

  $: displayInputButton = variant === VTMN_CHIP_VARIANT.INPUT;
  $: displayFilterBadge =
    variant === VTMN_CHIP_VARIANT.FILTER && badgeValue > 0;
  $: displayLeftIcon =
    [VTMN_CHIP_VARIANT.INPUT, VTMN_CHIP_VARIANT.ACTION].includes(variant) &&
    icon;

  const cancelClickHandler = (e) => {
    e.stopPropagation();
    dispatch('cancel');
  };
  const selectClickHandler = () => {
    if (disabled) {
      return;
    }
    dispatch('click');
  };
</script>

<div
  class={componentClass}
  role="button"
  aria-disabled={disabled}
  aria-pressed={isSelected && variant !== 'action'}
  on:click={selectClickHandler}
  on:keydown
  on:keyup
  on:keypress
  tabindex={disabled ? undefined : 0}
>
  {#if displayLeftIcon}
    <VtmnIcon value={icon} aria-hidden="true" />
  {/if}
  <slot />
  {#if displayInputButton}
    <VtmnButton
      variant="ghost-reversed"
      iconAlone="close-line"
      aria-label={$$restProps['aria-label']}
      {size}
      on:click={cancelClickHandler}
      {disabled}
    />
  {/if}
  {#if displayFilterBadge}
    <VtmnBadge value={badgeValue} />
  {/if}
</div>

<style lang="css">
  @import '@vtmn/css-chip';
</style>

// packages/sources/react/src/components/selection-controls/VtmnChip/VtmnChip.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-chip/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { VtmnChipSize, VtmnChipVariant } from './types';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon/VtmnIcon';
import { VtmnButton } from '../../actions/VtmnButton/VtmnButton';
import { VtmnBadge } from '../../indicators/VtmnBadge/VtmnBadge';

export interface VtmnChipProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * Called when clicking the chip
   * @type {React.MouseEventHandler}
   * @defaultValue undefined
   */
  onClick?: React.MouseEventHandler;

  /**
   * Called when the cross is clicked when using input variant
   * @type {React.MouseEventHandler}
   * @defaultValue undefined
   */
  onCancel?: React.MouseEventHandler;

  /**
   * The variant of the chip.
   * @defaultValue 'single-choice'
   */
  variant?: VtmnChipVariant;

  /**
   * The size of the chip.
   * @defaultValue 'medium'
   */
  size?: VtmnChipSize;

  /**
   * Disabled state of the chip.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;

  /**
   * Selected state of the chip.
   * @type {boolean}
   * @defaultValue false
   */
  selected?: boolean;

  /**
   * Icon to display on the chip
   * @type {VitamixId}
   * @defaultValue undefined
   */
  icon?: VitamixId;

  /**
   * Number to display in chip's badge
   * @type number
   * @defaultValue 0
   */
  badgeValue?: number;
}

export const VtmnChip = ({
  variant = 'single-choice',
  size = 'medium',
  disabled = false,
  selected = false,
  icon = undefined,
  badgeValue = 0,
  onClick,
  onCancel,
  children,
  className,
  ...props
}: VtmnChipProps) => {
  const isSelected = selected && ['single-choice', 'filter'].includes(variant);
  return (
    <div
      className={clsx(
        'vtmn-chip',
        `vtmn-chip_size--${size}`,
        `vtmn-chip_variant--${variant}`,
        disabled && 'vtmn-chip--disabled',
        isSelected && 'vtmn-chip--selected',
        className,
      )}
      role="button"
      aria-disabled={disabled}
      aria-pressed={isSelected && variant !== 'action'}
      onClick={(e) => {
        if (!disabled && onClick) {
          onClick(e);
        }
      }}
      {...props}
    >
      {icon && (variant === 'input' || variant === 'action') && (
        <VtmnIcon
          variant={selected && variant !== 'action' ? 'reversed' : 'default'}
          value={icon}
          aria-hidden="true"
        />
      )}

      {children}

      {variant == 'filter' && badgeValue != 0 && (
        <VtmnBadge variant="default" value={badgeValue} />
      )}

      {variant == 'input' && (
        <VtmnButton
          variant="ghost"
          iconAlone="close-line"
          disabled={disabled}
          size={size}
          onClick={(e) => {
            e.stopPropagation();
            onCancel?.(e);
          }}
        />
      )}
    </div>
  );
};

const MemoVtmnChip = React.memo(VtmnChip);

MemoVtmnChip.displayName = 'VtmnChip';

export default MemoVtmnChip;
