// packages/sources/react/src/components/indicators/VtmnTag/VtmnTag.tsx
import '@vtmn/css-tag/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import * as React from 'react';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon';
import { VtmnTagSize, VtmnTagVariant } from './types';

type VtmnTagAdditionalProps = {
  /**
   * The variant of the tag.
   * @defaultValue 'accent'
   */
  variant?: VtmnTagVariant;

  /**
   * The icon to display at the start  of the tag.
   * Only for 'input' variant
   */
  icon?: VitamixId;

  /**
   * The href that makes the tag interactive.
   * @type {string}
   */
  href?: string;

  /**
   * The size of the tag.
   * @defaultValue 'medium'
   */
  size?: VtmnTagSize;
};

export type VtmnTagProps = React.ComponentPropsWithoutRef<'span'> &
  React.ComponentPropsWithoutRef<'a'> &
  VtmnTagAdditionalProps;

export const VtmnTag = ({
  variant = 'accent',
  size = 'medium',
  icon,
  href,
  className,
  children,
  ...props
}: VtmnTagProps) => {
  return href ? (
    <a
      className={`vtmn-tag vtmn-tag_variant--${variant} vtmn-tag_size--${size} ${
        className ? className : ''
      }`}
      href={href}
      {...props}
    >
      {icon && (
        <VtmnIcon
          value={icon}
          aria-hidden="true"
          style={{ fontSize: 'inherit' }}
        />
      )}
      {children}
    </a>
  ) : (
    <span
      className={`vtmn-tag vtmn-tag_variant--${variant} vtmn-tag_size--${size} ${
        className ? className : ''
      }`}
      {...props}
    >
      {icon && (
        <VtmnIcon
          value={icon}
          aria-hidden="true"
          style={{ fontSize: 'inherit' }}
        />
      )}
      {children}
    </span>
  );
};

const MemoVtmnTag = React.memo(VtmnTag);

MemoVtmnTag.displayName = 'VtmnTag';

export default MemoVtmnTag;

// packages/sources/vue/src/components/indicators/VtmnTag/VtmnTag.vue
<script lang="ts">
import '@vtmn/css-tag/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnTagSize, VtmnTagVariant } from './types';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTag',
  inheritAttrs: false,
  components: { VtmnIcon },
  props: {
    href: {
      type: String as PropType<string>,
      default: undefined,
    },
    variant: {
      type: String as PropType<VtmnTagVariant>,
      default: 'accent',
      validator: (val: VtmnTagVariant) =>
        [
          'accent',
          'alert',
          'brand',
          'decorative_gravel',
          'decorative_brick',
          'decorative_saffron',
          'decorative_gold',
          'decorative_jade',
          'decorative_emerald',
          'decorative_cobalt',
          'decorative_amethyst',
        ].includes(val),
    },
    icon: {
      type: String as PropType<VitamixId>,
      default: null,
    },
    size: {
      type: String as PropType<VtmnTagSize>,
      default: 'medium',
      validator: (val: VtmnTagSize) =>
          ['small', 'medium'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
      classes: computed(() => ({
        'vtmn-tag': true,
        [`vtmn-tag_variant--${props.variant}`]: props.variant,
        [`vtmn-tag_size--${props.size}`]: true,
      })),
    };
  },
});
</script>

<template>
  <a v-if="href" :href="href" :class="classes" v-bind="$attrs"
    ><VtmnIcon v-if="icon" :value="icon" :style="styleObject" /><slot
  /></a>
  <span v-else :class="classes" v-bind="$attrs"
    ><VtmnIcon v-if="icon" :value="icon" :style="styleObject" /><slot
  /></span>
</template>
