// packages/sources/vue/src/components/overlays/VtmnPopover/VtmnPopover.vue
<script lang="ts">
import '@vtmn/css-popover/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';
import { VtmnPopoverPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnPopover',
  inheritAttrs: false,
  props: {
    id: {
      type: String as PropType<string>,
      required: true,
    },
    position: {
      type: String as PropType<VtmnPopoverPosition>,
      default: 'top',
      validator: (val: VtmnPopoverPosition) =>
        [
          'top-left',
          'top',
          'top-right',
          'right',
          'bottom-right',
          'bottom',
          'bottom-left',
          'left',
        ].includes(val),
    },
    title: {
      type: String as PropType<string>,
    },
    body: {
      type: String as PropType<string>,
    },
  },
});
</script>

<template>
  <div
    class="vtmn-popover"
    :data-position="position"
    :aria-describedby="id"
    tabindex="0"
    v-bind="$attrs"
  >
    <slot />

    <div :id="id" role="tooltip">
      <p class="vtmn-popover_title">{{ title }}</p>
      <p class="vtmn-popover_text">{{ body }}</p>
    </div>
  </div>
</template>

// packages/sources/svelte/src/components/VtmnPopover.svelte
<script context="module">
  /** @enum */
  export const POSITION = {
    TOP_LEFT: 'top-left',
    TOP: 'top',
    TOP_RIGHT: 'top-right',
    RIGHT: 'right',
    BOTTOM_RIGHT: 'bottom-right',
    BOTTOM: 'bottom',
    BOTTOM_LEFT: 'bottom-left',
    LEFT: 'left',
  };

  /** @type {POSITION} */
  export const DEFAULT_POSITION = POSITION.BOTTOM;
</script>

<script>
  import '@vtmn/css-popover/dist/index.css';
  import { cn } from '../utils/classnames';

  /** @type {string} - An unique id */
  export let id = '';
  /** @type {POSITION} */
  export let position = DEFAULT_POSITION;

  let className;
  /**
   * @type {string} A custom class to apply to the component.
   */
  export { className as class };

  $: componentClass = cn('vtmn-popover', className);
</script>

<div
  class={componentClass}
  data-position={position}
  aria-describedby={id}
  tabindex="0"
  {...$$restProps}
>
  <slot name="placeholder" />

  <div {id} role="tooltip">
    <p class="vtmn-popover_title"><slot name="title" /></p>
    <p class="vtmn-popover_text"><slot name="body" /></p>
  </div>
</div>
