// packages/sources/web-components/src/components/vtmn-button/vtmn-button.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';

@Component({
  tag: 'vtmn-button',
  styleUrl: 'vtmn-button.pcss',
})
export class VtmnButton implements ComponentInterface {
  /**
   * The variant of the button.
   * @default 'primary'
   */
  @Prop() variant:
    | 'primary'
    | 'primary-reversed'
    | 'secondary'
    | 'tertiary'
    | 'ghost'
    | 'ghost-reversed'
    | 'conversion' = 'primary';

  /**
   * The size of the button.
   * @default 'medium'
   */
  @Prop() size: 'small' | 'medium' | 'large' | 'stretched' = 'medium';

  /**
   * Icon to display on the left hand side of button
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  @Prop({ attribute: 'iconleft' }) iconLeft: VitamixId;

  /**
   * Icon to display on the right hand side of button
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  @Prop({ attribute: 'iconright' }) iconRight: VitamixId;

  /**
   * Icon to display when it is a button with icon only
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  @Prop({ attribute: 'iconalone' }) iconAlone: VitamixId;

  render() {
    return (
      <button
        class={`vtmn-btn vtmn-btn_variant--${this.variant} vtmn-btn_size--${
          this.size
        }
        ${!this.iconAlone && this.iconLeft ? 'vtmn-btn--icon-left' : ''} ${
          !this.iconAlone && this.iconRight ? 'vtmn-btn--icon-right' : ''
        } ${this.iconAlone ? 'vtmn-btn--icon-alone' : ''}`}
        type="button">
        {this.iconLeft && <span class={`vtmx-${this.iconLeft}`}></span>}
        {this.iconAlone ? (
          <span class={`vtmx-${this.iconAlone}`}></span>
        ) : (
          <slot></slot>
        )}
        {this.iconRight && <span class={`vtmx-${this.iconRight}`}></span>}
      </button>
    );
  }
}

// packages/sources/svelte/src/components/VtmnButton.svelte
<script>
  import '@vtmn/css-button/dist/index.css';

  /**
   * The variant of the button.
   * @type {'primary' | 'primary-reversed' | 'secondary' | 'tertiary' | 'ghost' | 'ghost-reversed' | 'conversion'}
   * @default 'primary'
   */
  export let variant = 'primary';
  /**
   * The size of the button.
   * @type {'small' | 'medium' | 'large' | 'stretched'}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Icon to display on the left hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconLeft;

  /**
   * Icon to display on the right hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconRight;

  /**
   * Icon to display when it is a button with icon only
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconAlone;
</script>

<button
  type="button"
  class={['vtmn-btn',
    `vtmn-btn_variant--${variant}`,
    `vtmn-btn_size--${size}`,
    !iconAlone && iconLeft ? 'vtmn-btn--icon-left' : '',
    !iconAlone && iconRight ? 'vtmn-btn--icon-right' : '',
    iconAlone ? 'vtmn-btn--icon-alone' : '']
    .join(' ')}
  {...$$props}>
  {#if !iconAlone && iconLeft}
    <span class={`vtmx-${iconLeft}`}></span>
  {/if}
  {#if iconAlone}
    <span class={`vtmx-${iconAlone}`}></span>
  {:else}
    <slot></slot>
  {/if}
  {#if !iconAlone && iconRight}
    <span class={`vtmx-${iconRight}`}></span>
  {/if}
</button>
