// packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx
import * as React from 'react';
import clsx from 'clsx';

import '@vtmn/css-text-input';
import { VtmnIcon } from '../VtmnIcon';

export interface VtmnTextInputProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * ID of the input
   * @type {string}
   */
  id: string;

  /**
   * Label text linked to the input
   * @type {string}
   */
  labelText: string;

  /**
   * Helper text to help the user
   * @type {string}
   * @defaultValue undefined and therefore not displayed by default
   */
  helperText?: string;

  /**
   * Placeholder
   * @type {string}
   */
  placeholder?: string;

  /**
   * Icon
   * @type {string}
   * @defaultValue undefined and therefore not displayed by default
   */
  icon?: string;

  /**
   * Is a TextArea
   * @type {boolean}
   * @defaultValue false (Input)
   */
  multiline?: boolean;

  /**
   * Whether input is successful or not
   * @type {boolean}
   * @defaultValue false
   */
  valid?: boolean;

  /**
   * Whether input is in error or not
   * @type {boolean}
   * @defaultValue false
   */
  error?: boolean;
}

export const VtmnTextInput = ({
  className,
  disabled = false,
  error = false,
  helperText,
  icon = undefined,
  id,
  labelText,
  multiline = false,
  placeholder,
  valid = false,
  ...props
}: VtmnTextInputProps) => {
  return (
    <>
      <label className="vtmn-text-input_label" htmlFor={id}>
        {labelText}
      </label>

      <div className="vtmn-text-input_container">
        {multiline ? (
          <textarea
            className={clsx(
              'vtmn-text-input',
              className,
              { 'vtmn-text-input--valid': valid && !disabled },
              { 'vtmn-text-input--error': error && !disabled },
            )}
            id={id}
            placeholder={placeholder}
            disabled={disabled}
            {...props}
          />
        ) : (
          <>
            <input
              className={clsx(
                'vtmn-text-input',
                className,
                { 'vtmn-text-input--valid': valid && !disabled },
                { 'vtmn-text-input--error': error && !disabled },
              )}
              id={id}
              type="text"
              placeholder={placeholder}
              disabled={disabled}
              {...props}
            />
            <VtmnIcon value={icon} />
          </>
        )}
      </div>

      {helperText && (
        <p className="vtmn-text-input_helper-text">{helperText}</p>
      )}
    </>
  );
};

export default React.memo(VtmnTextInput);

// packages/sources/svelte/src/components/VtmnTextInput.svelte
<script>
  import '@vtmn/css-text-input';

  /** @restProps { input | textarea } */

  /**
   * ID of the input
   * @type {string}
   */
  export let identifier;

  /**
   * Label text linked to the input
   * @type {string}
   */
  export let labelText;

  /**
   * Plaholder of the input
   * @type {string}
   */
  export let placeholder;

  /**
   * Whether input should be disabled or not
   * @type {boolean}
   */
  export let disabled = false;

  /**
   * Helper text to help the user
   * @type {string}
   */
  export let helperText;

  /**
   * Whether input is multiline or not
   * @type {boolean}
   */
  export let multiline = false;

  /**
   * Whether input is successful or not
   * @type {boolean}
   */
  export let valid = false;

  /**
   * Whether input is in error or not
   * @type {boolean}
   */
  export let error = false;

  /**
   * Icon to be displayed
   * @type {string}
   */
  export let icon;

  /**
   * The value of the input
   * @type {string}
   */
  export let value;
</script>

{#if labelText}
  <label class="vtmn-text-input_label" for={identifier}>{labelText}</label>
{/if}
{#if multiline}
  <textarea
    bind:value
    class="vtmn-text-input"
    class:vtmn-text-input--error={error}
    class:vtmn-text-input--valid={valid}
    id={identifier}
    {disabled}
    {placeholder}
    {...$$restProps}
  />
{:else}
  <div class="vtmn-text-input_container">
    <input
      bind:value
      class="vtmn-text-input"
      class:vtmn-text-input--valid={valid}
      class:vtmn-text-input--error={error}
      type="text"
      id={identifier}
      {disabled}
      {placeholder}
      {...$$restProps}
    />
    <span class={icon && `vtmx-${icon}`} />
  </div>
{/if}
{#if helperText}
  <p
    class="vtmn-text-input_helper-text"
    class:vtmn-text-input_helper-text--error={error}
  >
    {helperText}
  </p>
{/if}
