// packages/sources/vue/src/components/VtmnTextInput/VtmnTextInput.vue
<script lang="ts">
import '@vtmn/css-text-input/dist/index.css';
import { reactive, computed, defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTextInput',
  props: {
    identifier: {
      type: String,
      default: null,
    },
    labelText: {
      type: String,
      default: null,
    },
    placeholder: {
      type: String,
      default: null,
    },
    helperText: {
      type: String,
      default: null,
    },
    multiline: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    valid: {
      type: Boolean,
      default: false,
    },
    error: {
      type: Boolean,
      default: false,
    },
    icon: {
      type: String,
      default: null,
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-text-input': true,
        'vtmn-text-input--error': props.error,
        'vtmn-text-input--valid': props.valid,
      })),
      helperClasses: computed(() => ({
        'vtmn-text-input_helper-text': true,
        'vtmn-text-input_helper-text--error': props.error,
      })),
      iconClass: computed(() => ({
        [`vtmx-${props.icon}`]: props.icon,
      })),
    };
  },
});
</script>

<template>
  <label class="vtmn-text-input_label" :for="this.identifier">
    {{ this.labelText }}
  </label>
  <textarea
    v-if="this.multiline"
    :class="classes"
    :id="this.identifier"
    :placeholder="this.placeholder"
    :disabled="this.disabled"
  ></textarea>
  <div v-if="!this.multiline" class="vtmn-text-input_container">
    <input
      type="text"
      :class="classes"
      :id="this.identifier"
      :placeholder="this.placeholder"
      :disabled="this.disabled"
    />
    <span :v-if="this.icon" :class="iconClass"></span>
  </div>
  <p :class="helperClasses">
    {{ this.helperText }}
  </p>
</template>

// packages/sources/svelte/src/components/VtmnTextInput.svelte
<script>
  import '@vtmn/css-text-input/dist/index.css';

  /**
   * ID of the input
   * @type {string}
   */
  export let identifier;

  /**
   * Label text linked to the input
   * @type {string}
   */
  export let labelText;

  /**
   * Plaholder of the input
   * @type {string}
   */
  export let placeholder;

  /**
   * Whether input should be disabled or not
   * @type {boolean}
   */
  export let disabled = false;

  /**
   * Helper text to help the user
   * @type {string}
   */
  export let helperText;

  /**
   * Whether input is multiline or not
   * @type {boolean}
   */
  export let multiline = false;

  /**
   * Whether input is successful or not
   * @type {boolean}
   */
  export let valid = false;

  /**
   * Whether input is in error or not
   * @type {boolean}
   */
  export let error = false;

  /**
   * Icon to be displayed
   * @type {string}
   */
  export let icon;
</script>

{#if labelText}
  <label class="vtmn-text-input_label" for={identifier}>{labelText}</label>
{/if}
{#if multiline}
  <textarea
    class="vtmn-text-input"
    class:vtmn-text-input--error={error}
    class:vtmn-text-input--valid={valid}
    {identifier}
    {disabled}
    {placeholder}
    {...$$props}
  />
{:else}
  <div class="vtmn-text-input_container">
    <input
      class="vtmn-text-input"
      class:vtmn-text-input--valid={valid}
      class:vtmn-text-input--error={error}
      type="text"
      {identifier}
      {disabled}
      {placeholder}
      {...$$props}
    />
    <span class={icon && `vtmx-${icon}`} />
  </div>
  {#if helperText}
    <p
      class="vtmn-text-input_helper-text"
      class:vtmn-text-input_helper-text--error={error}
    >
      {helperText}
    </p>
  {/if}
{/if}
