// packages/sources/vue/src/components/VtmnButton/VtmnButton.vue
<script lang="ts">
import '@vtmn/css-button/dist/index-with-vars.css';
import { reactive, computed, defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnButton',
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: (val: string) =>
        [
          'primary',
          'primary-reversed',
          'secondary',
          'tertiary',
          'ghost',
          'ghost-reversed',
          'conversion',
        ].includes(val),
    },
    size: {
      type: String,
      default: 'medium',
      validator: (val: string) =>
        ['small', 'medium', 'large', 'stretched'].includes(val),
    },
    iconLeft: {
      type: String,
      default: null,
    },
    iconRight: {
      type: String,
      default: null,
    },
    iconAlone: {
      type: String,
      default: null,
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-btn': true,
        [`vtmn-btn_variant--${props.variant}`]: true,
        [`vtmn-btn_size--${props.size}`]: true,
        'vtmn-btn--icon-left': !props.iconAlone && props.iconLeft,
        'vtmn-btn--icon-right': !props.iconAlone && props.iconRight,
        'vtmn-btn--icon-alone': props.iconAlone,
      })),
      iconLeftClass: computed(() => ({
        [`vtmx-${props.iconLeft}`]: props.iconLeft,
      })),
      iconRightClass: computed(() => ({
        [`vtmx-${props.iconRight}`]: props.iconRight,
      })),
      iconAloneClass: computed(() => ({
        [`vtmx-${props.iconAlone}`]: props.iconAlone,
      })),
    };
  },
});
</script>

<template>
  <button type="button" :class="classes" v-bind="$attrs">
    <span
      :v-if="!this.iconAlone && this.iconLeft"
      :class="iconLeftClass"
    ></span>
    <span :v-if="this.iconAlone" :class="iconAloneClass"></span>
    <slot :v-if="!this.iconAlone"></slot>
    <span
      :v-if="!this.iconAlone && this.iconRight"
      :class="iconRightClass"
    ></span>
  </button>
</template>

// packages/sources/svelte/src/components/VtmnButton.svelte
<script>
  import '@vtmn/css-button/dist/index.css';

  /**
   * The variant of the button.
   * @type {'primary' | 'primary-reversed' | 'secondary' | 'tertiary' | 'ghost' | 'ghost-reversed' | 'conversion'}
   * @default 'primary'
   */
  export let variant = 'primary';
  /**
   * The size of the button.
   * @type {'small' | 'medium' | 'large' | 'stretched'}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Icon to display on the left hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconLeft;

  /**
   * Icon to display on the right hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconRight;

  /**
   * Icon to display when it is a button with icon only
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconAlone;
</script>

<button
  type="button"
  class={['vtmn-btn',
    `vtmn-btn_variant--${variant}`,
    `vtmn-btn_size--${size}`,
    !iconAlone && iconLeft ? 'vtmn-btn--icon-left' : '',
    !iconAlone && iconRight ? 'vtmn-btn--icon-right' : '',
    iconAlone ? 'vtmn-btn--icon-alone' : '']
    .join(' ')}
  {...$$props}>
  {#if !iconAlone && iconLeft}
    <span class={`vtmx-${iconLeft}`}></span>
  {/if}
  {#if iconAlone}
    <span class={`vtmx-${iconAlone}`}></span>
  {:else}
    <slot></slot>
  {/if}
  {#if !iconAlone && iconRight}
    <span class={`vtmx-${iconRight}`}></span>
  {/if}
</button>
