// packages/sources/web-components/src/components/vtmn-link/vtmn-link.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';

@Component({
  tag: 'vtmn-link',
  styleUrl: 'vtmn-link.pcss',
})
export class VtmnLink implements ComponentInterface {
  /**
   * The size of the link.
   * @default null
   */
  @Prop() size: 'small' | 'medium' | 'large';

  /**
   * Is the link standalone or not
   * @default null
   */
  @Prop() standalone: boolean;

  /**
   * Is the link has an icon or not
   * @default null
   */
  @Prop({ attribute: 'iconalong' }) iconAlong: boolean;

  /**
   * The hypertext link
   * @default '#'
   */
  @Prop() href: string = '#';

  /**
   * The target of the link
   * @default null
   */
  @Prop() target: string;

  render() {
    return (
      <a
        href={this.href}
        target={this.target}
        class={[
          'vtmn-link',
          `vtmn-link_size--${this.size}`,
          this.standalone && 'vtmn-link--standalone',
          this.standalone && this.iconAlong && 'vtmn-link--icon-along',
        ]
          .filter(Boolean)
          .join(' ')}
      >
        <slot></slot>
      </a>
    );
  }
}

// packages/sources/svelte/src/components/VtmnLink.svelte
<script>
  import '@vtmn/css-link';

  /**
   * The href of the link.
   * @type {string}
   * @default '#'
   */
  export let href = '#';

  /**
   * The target of the link.
   * @type {string}
   * @default '_self'
   */
  export let target = '_target';

  /**
   * The size of the link.
   * @type {string}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Whether link is standalone or not.
   * @type {boolean}
   * @default false
   */
  export let standalone = false;

  /**
   * Whether link has an icon or not.
   * @type {boolean}
   * @default false
   */
  export let iconAlong = false;
</script>

<a
  {href}
  {target}
  class={[
    'vtmn-link',
    `vtmn-link_size--${size}`,
    standalone && 'vtmn-link--standalone',
    standalone && iconAlong && 'vtmn-link--icon-along',
  ]
    .filter(Boolean)
    .join(' ')}
  {...$$props}
>
  <slot />
</a>
