// packages/sources/react/src/components/VtmnButton/VtmnButton.tsx
import * as React from 'react';
import '@vtmn/css-button/dist/index-with-vars.css';
import { VtmnButtonVariant, VtmnButtonSize } from './types';
import { VtmnIcon } from '../VtmnIcon';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';

export interface VtmnButtonProps
  extends React.ComponentPropsWithoutRef<'button'> {
  /**
   * The variant of the button.
   * @default 'primary'
   */
  variant?: VtmnButtonVariant;
  /**
   * The size of the button.
   * @default 'medium'
   */
  size?: VtmnButtonSize;

  /**
   * Icon to display on the left hand side of button
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  iconLeft?: VitamixId;

  /**
   * Icon to display on the right hand side of button
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  iconRight?: VitamixId;

  /**
   * Icon to display when it is a button with icon only
   * @type {VitamixId}
   * @default undefined and therefore not displayed by default
   */
  iconAlone?: VitamixId;
}

export const VtmnButton = ({
  variant = 'primary',
  size = 'medium',
  iconLeft,
  iconRight,
  iconAlone,
  children,
  className,
  ...props
}: VtmnButtonProps) => {
  return (
    <button
      className={`vtmn-btn vtmn-btn_variant--${variant} vtmn-btn_size--${size} ${
        className ? className : ''
      } ${!iconAlone && iconLeft ? 'vtmn-btn--icon-left' : ''} ${
        !iconAlone && iconRight ? 'vtmn-btn--icon-right' : ''
      } ${iconAlone ? 'vtmn-btn--icon-alone' : ''}`}
      {...props}
    >
      {!iconAlone && iconLeft && (
        <VtmnIcon
          value={iconLeft}
          style={{ color: 'inherit', fontSize: 'inherit' }}
        />
      )}
      {iconAlone ? (
        <VtmnIcon
          value={iconAlone}
          style={{ color: 'inherit', fontSize: 'inherit' }}
        />
      ) : (
        children
      )}
      {!iconAlone && iconRight && (
        <VtmnIcon
          value={iconRight}
          style={{ color: 'inherit', fontSize: 'inherit' }}
        />
      )}
    </button>
  );
};

export default React.memo(VtmnButton);

// packages/sources/svelte/src/components/VtmnButton.svelte
<script>
  import '@vtmn/css-button/dist/index.css';

  /**
   * The variant of the button.
   * @type {'primary' | 'primary-reversed' | 'secondary' | 'secondary-reversed' | 'ghost' | 'conversion'}
   * @default 'primary'
   */
  export let variant = 'primary';
  /**
   * The size of the button.
   * @type {'small' | 'medium' | 'large' | 'stretched'}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Icon to display on the left hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconLeft;

  /**
   * Icon to display on the right hand side of button
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconRight;

  /**
   * Icon to display when it is a button with icon only
   * @type string
   * @default undefined and therefore not displayed by default
   */
  export let iconAlone;
</script>

<button
  type="button"
  class={['vtmn-btn',
    `vtmn-btn_variant--${variant}`,
    `vtmn-btn_size--${size}`,
    !iconAlone && iconLeft ? 'vtmn-btn--icon-left' : '',
    !iconAlone && iconRight ? 'vtmn-btn--icon-right' : '',
    iconAlone ? 'vtmn-btn--icon-alone' : '']
    .join(' ')}
  {...$$props}>
  {#if !iconAlone && iconLeft}
    <span class={`vtmx-${iconLeft}`}></span>
  {/if}
  {#if iconAlone}
    <span class={`vtmx-${iconAlone}`}></span>
  {:else}
    <slot></slot>
  {/if}
  {#if !iconAlone && iconRight}
    <span class={`vtmx-${iconRight}`}></span>
  {/if}
</button>
