// packages/sources/vue/src/components/navigation/VtmnBreadcrumbItem/VtmnBreadcrumbItem.vue
<script lang="ts">
import '@vtmn/css-breadcrumb/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { defineComponent, PropType } from 'vue';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnBreadcrumbItem',
  components: { VtmnIcon },
  props: {
    icon: {
      type: String as PropType<VitamixId>,
      default: null,
    },
    href: {
      type: String as PropType<string>,
      default: '#',
    },
  },
  setup() {
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
    };
  },
});
</script>

<template>
  <li>
    <VtmnIcon
      v-if="icon"
      :value="icon"
      :style="styleObject"
      aria-hidden="true"
    />
    <a v-if="href" :href="href" v-bind="$attrs">
      <slot />
    </a>
    <slot v-else />
  </li>
</template>

// packages/sources/react/src/components/navigation/VtmnBreadcrumb/VtmnBreadcrumbItem.tsx
import '@vtmn/css-breadcrumb/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import * as React from 'react';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon';

export interface VtmnBreadcrumbItemProps
  extends React.ComponentPropsWithoutRef<'nav'> {
  /**
   * The leading icon of the breadcrumb item.
   * @defaultValue null
   */
  icon?: VitamixId;

  /**
   * The href of the breadcrumb item.
   * @defaultValue null
   */
  href?: string;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnBreadcrumbItem = ({
  icon,
  href,
  children,
  ...props
}: VtmnBreadcrumbItemProps) => {
  return (
    <li {...props}>
      {icon ? (
        <VtmnIcon
          value={icon}
          aria-hidden="true"
          style={{ color: 'inherit', fontSize: 'inherit' }}
        />
      ) : null}
      {href ? <a href={href}>{children}</a> : children}
    </li>
  );
};

const MemoVtmnBreadcrumbItem = React.memo(VtmnBreadcrumbItem);

MemoVtmnBreadcrumbItem.displayName = 'VtmnBreadcrumbItem';

export default MemoVtmnBreadcrumbItem;
