// packages/sources/react/src/components/indicators/VtmnLoader/VtmnLoader.tsx
import * as React from 'react';
import '@vtmn/css-loader';
import { VtmnLoaderSize } from './types';

export interface VtmnLoaderProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The size of the loader.
   * @defaultValue 'medium'
   */
  size?: VtmnLoaderSize;
}

export const VtmnLoader = ({
  size = 'medium',
  className,
  ...props
}: VtmnLoaderProps) => {
  return (
    <div
      className={`vtmn-loader vtmn-loader_size--${size} ${className}`}
      {...props}
    ></div>
  );
};

const MemoVtmnLoader = React.memo(VtmnLoader);

MemoVtmnLoader.displayName = 'VtmnLoader';

export default MemoVtmnLoader;

// packages/sources/web-components/src/components/vtmn-loader/vtmn-loader.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';

@Component({
  tag: 'vtmn-loader',
  styleUrl: 'vtmn-loader.pcss',
})
export class VtmnLoader implements ComponentInterface {
  /**
   * The size of the loader.
   * @type {string}
   * @defaultValue 'medium'
   */
  @Prop() size: 'small' | 'medium' | 'large' = 'medium';

  render() {
    return (
      <div
        class={['vtmn-loader', `vtmn-loader_size--${this.size}`].join(' ')}
      ></div>
    );
  }
}
