// packages/sources/react/src/components/overlays/VtmnModal/VtmnModal.tsx
import * as React from 'react';
import '@vtmn/css-modal/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton/VtmnButton';

export interface VtmnModalProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * Whether to open the modal or not
   * @type {boolean}
   * @default false
   */
  open?: boolean;

  /**
   * Called when user action should close the modal
   * @type {void}
   * @default undefined
   */
  onClose?: () => void;
}
export const VtmnModal = ({
  open = false,
  onClose = undefined,
  children,
  className,
  ...props
}: VtmnModalProps) =>
  open ? (
    <div
      className={clsx('vtmn-modal', className)}
      role="dialog"
      aria-modal="true"
      aria-labelledby="vtmn-modal-title"
      aria-describedby="vtmn-modal-description"
      {...props}
    >
      <div className="vtmn-modal_background-overlay" onClick={onClose} />

      <div className="vtmn-modal_content">
        {/**
         * Renders every child and inject onClose in VtmnModalTitle
         */}
        {React.Children.map(children, (child: React.ReactNode) =>
          React.isValidElement(child) && child.type === VtmnModalTitle
            ? React.cloneElement(child, { ...child.props, onClose })
            : child,
        )}
      </div>
    </div>
  ) : null;

export interface VtmnModalTitleProps
  extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * Called when user action should close the modal
   * @type {void}
   * @default undefined
   */
  onClose?: () => void;
}
export const VtmnModalTitle = ({
  onClose = undefined,
  children,
  className,
  ...props
}: VtmnModalTitleProps) => (
  <div className={clsx('vtmn-modal_content_title', className)} {...props}>
    <p className="vtmn-modal_content_title--text">{children}</p>
    <VtmnButton variant="ghost" iconAlone="close-fill" onClick={onClose} />
  </div>
);

export const VtmnModalDescription = ({
  children,
  className,
  ...props
}: React.ComponentPropsWithoutRef<'div'>) => (
  <div className={clsx('vtmn-modal_content_body', className)} {...props}>
    <p className="vtmn-modal_content_body--text">{children}</p>
  </div>
);

export const VtmnModalActions = ({
  children,
  className,
  ...props
}: React.ComponentPropsWithoutRef<'div'>) => (
  <div className={clsx('vtmn-modal_content_actions', className)} {...props}>
    {children}
  </div>
);

const MemoVtmnModal = React.memo(VtmnModal);

MemoVtmnModal.displayName = 'VtmnModal';

export default MemoVtmnModal;

// packages/sources/vue/src/components/overlays/VtmnModal/VtmnModal.vue
<script lang="ts">
import '@vtmn/css-modal/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnModal',
  components: { VtmnButton },
  inheritAttrs: false,
  props: {
    open: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  emits: ['close'],
  setup(props, { emit }) {
    props = reactive(props);

    const handleClose = () => {
      return emit('close');
    };

    return {
      classes: computed(() => ({
        'vtmn-modal': true,
      })),
      handleClose,
    };
  },
});
</script>

<template>
  <div
    v-if="open"
    :class="classes"
    role="dialog"
    aria-modal="true"
    v-bind="$attrs"
  >
    <div class="vtmn-modal_background-overlay" @click.prevent="handleClose" />
    <div class="vtmn-modal_content">
      <div class="vtmn-modal_content_title">
        <span v-if="$slots.title" class="vtmn-modal_content_title--text">
          <slot name="title" />
        </span>
        <VtmnButton
          aria-label="close"
          variant="ghost"
          size="medium"
          iconAlone="close-line"
          @click.prevent="handleClose"
        />
      </div>

      <div v-if="$slots.description" class="vtmn-modal_content_body">
        <slot name="description" />
      </div>

      <div v-if="$slots.actions" class="vtmn-modal_content_actions">
        <slot name="actions" />
      </div>
    </div>
  </div>
</template>
