// packages/sources/vue/src/components/actions/VtmnDropdownItem/VtmnDropdownItem.vue
<script lang="ts">
import '@vtmn/css-dropdown/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { defineComponent, PropType } from 'vue';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';
import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnDropdownItem',
  components: { VtmnIcon, VtmnDivider },
  props: {
    selected: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    divider: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    icon: {
      type: String as PropType<VitamixId>,
      default: null,
    },
  },
  emits: ['update:modelValue'],
  setup(_, { attrs, emit }) {
    const labelId = attrs['id'] ? String(attrs['id']) : undefined;

    const handleChange = (event: Event) => {
      if (event && event.target) {
        return emit(
          'update:modelValue',
          (event.target as HTMLInputElement).checked,
        );
      }
    };

    return {
      labelId,
      handleChange,
    };
  },
});
</script>

<template>
  <input
    type="checkbox"
    :cheched="selected"
    @change="handleChange"
    v-bind="$attrs"
  />
  <label :for="labelId">
    <VtmnIcon v-if="icon" :value="icon" aria-hidden="true" />
    <slot />
    <template v-if="$slots['endText']">
      <span class="vtmn-dropdown_item_label--end-text">
        <slot name="endText" />
      </span>
    </template>
  </label>
  <VtmnDivider v-if="divider" orientation="horizontal" role="separator" />
</template>

// packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdownItem.tsx
import '@vtmn/css-dropdown/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import * as React from 'react';
import { VtmnDivider } from '../../structure/VtmnDivider/VtmnDivider';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon';

export interface VtmnDropdownItemProps
  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'onChange'> {
  /**
   * Whether there is a divider at the end of the dropdown item.
   * @defaultValue false
   */
  divider?: boolean;

  /**
   * The leading icon of the dropdown item.
   * @defaultValue undefined
   */
  icon?: VitamixId;

  /**
   * End text of a dropdown option.
   * @defaultValue undefined
   */
  endText?: string;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;

  /**
   * Called when item has changed
   * @type {void}
   * @defaultValue undefined
   */
  onChange?: (event: React.ChangeEvent) => void;
}

export const VtmnDropdownItem = ({
  divider = false,
  icon,
  endText,
  children,
  onChange,
  ...props
}: VtmnDropdownItemProps) => {
  const [selected, setSelected] = React.useState(false);

  return (
    <React.Fragment>
      <input
        type="checkbox"
        checked={selected}
        onChange={(e) =>
          setSelected(() => {
            if (onChange) onChange(e);
            return !selected;
          })
        }
        {...props}
      />
      <label htmlFor={props['id'] ?? undefined}>
        {icon ? <VtmnIcon value={icon} /> : null}
        {children}
        {endText ? (
          <span className="vtmn-dropdown_item_label--end-text">{endText}</span>
        ) : null}
      </label>
      {divider ? (
        <VtmnDivider orientation="horizontal" role="separator" />
      ) : null}
    </React.Fragment>
  );
};

const MemoVtmnDropdownItem = React.memo(VtmnDropdownItem);

MemoVtmnDropdownItem.displayName = 'VtmnDropdownItem';

export default MemoVtmnDropdownItem;
