// packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToast.svelte
<script>
  import { vtmnToastStore } from './vtmnToast';
  import { VtmnButton } from '../../';
</script>

{#each $vtmnToastStore as toast, index}
  <div
    class="vtmn-toast "
    class:show={toast.show}
    class:vtmn-toast--with-icon-info={toast.withIcon}
    role="status"
    style={`--toast-position:${index * 80}px`}
  >
    <div class="vtmn-toast_content">{toast.content}</div>
    {#if toast.withCloseButton}
      <VtmnButton
        on:click={() => vtmnToastStore.close(toast)}
        aria-label="Close alert"
        variant="ghost-reversed"
        size="small"
        iconAlone="close-line"
      />
    {/if}
  </div>
{/each}

<style>
  @import '@vtmn/css-toast';
  .vtmn-toast {
    transform: translate(50%, calc(-50% - var(--toast-position)));
  }
</style>

// packages/sources/vue/src/components/overlays/VtmnToast/VtmnToast.vue
<script lang="ts">
import '@vtmn/css-toast/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnToast',
  inheritAttrs: false,
  components: { VtmnButton },
  props: {
    withIcon: {
      type: Boolean,
      default: false,
    },
    content: {
      type: String,
      required: true,
    },
    withCloseButton: {
      type: Boolean,
      default: false,
    },
    timeout: {
      type: Number,
      default: 8000,
    },
  },
  setup(props) {
    props = reactive(props);

    const handleClose = () => {
      return props.closeCallback();
    };

    return {
      classes: computed(() => ({
        'vtmn-toast': true,
        show: true,
        [`vtmn-toast--with-icon-info`]: props.withIcon,
      })),
      handleClose,
    };
  },
});
</script>

<template>
  <div :class="classes" role="status" v-bind="$attrs">
    <div class="vtmn-toast_content">{{ content }}</div>
    <VtmnButton
      v-if="withCloseButton"
      iconAlone="close-line"
      variant="ghost-reversed"
      size="small"
      aria-label="close"
      @click.prevent="handleClose"
    />
  </div>
</template>
