// packages/sources/svelte/src/components/navigation/VtmnTabs/VtmnTabs.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.svelte';
  import { VTMN_TABS_ALIGN, VTMN_TABS_SIZE } from './enums';

  /**
   * @type {'start' | 'center' | 'end'}
   * @defaultValue 'start'
   */
  export let align = VTMN_TABS_ALIGN.START;

  /**
   * @type {'small' | 'medium'}
   * @defaultValue 'medium'
   */
  export let size = VTMN_TABS_SIZE.MEDIUM;

  /**
   * Custom classes to apply to the component.
   * @type {string}
   */
  export let className = '';

  $: componentClass = cn(
    'vtmn-tabs',
    align && `vtmn-tabs_align--${align}`,
    size && `vtmn-tabs_size--${size}`,
    className,
  );
</script>

<nav class={componentClass} {...$$restProps}>
  <ul role="tablist">
    <slot />
  </ul>
  <VtmnDivider />
</nav>

<style lang="css">
  @import '@vtmn/css-tabs';
</style>

// packages/sources/vue/src/components/navigation/VtmnTabs/VtmnTabs.vue
<script lang="ts">
import '@vtmn/css-tabs/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.vue';

import { VtmnTabsAlign, VtmnTabsSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTabs',
  components: { VtmnDivider },
  props: {
    align: {
      type: String as PropType<VtmnTabsAlign>,
      default: 'start',
      validator: (val: VtmnTabsAlign) =>
        ['start', 'center', 'end'].includes(val),
    },
    size: {
      type: String as PropType<VtmnTabsSize>,
      default: 'medium',
      validator: (val: VtmnTabsSize) => ['small', 'medium'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-tabs': true,
        [`vtmn-tabs_align--${props.align}`]: props.align,
        [`vtmn-tabs_size--${props.size}`]: props.size,
      })),
    };
  },
});
</script>

<template>
  <nav :class="classes" v-bind="$attrs">
    <ul role="tablist">
      <slot />
    </ul>
    <VtmnDivider />
  </nav>
</template>
