// packages/sources/web-components/src/components/vtmn-badge/vtmn-badge.tsx
import { Component, Prop, h, ComponentInterface } from '@stencil/core';

@Component({
  tag: 'vtmn-badge',
  styleUrl: 'vtmn-badge.pcss',
})
export class VtmnBadge implements ComponentInterface {
  /**
   * The variant of the badge.
   * @default 'default'
   */
  @Prop() variant: 'default' | 'brand' | 'reversed' | 'accent' = 'default';

  /**
   * The target of the badge
   * @default 0
   */
  @Prop() value: number = 0;

  render() {
    return (
      <span
        class={`vtmn-badge vtmn-badge_variant--${this.variant}
        ${
          !this.value || this.value < 0
            ? 'vtmn-badge_size--without-value'
            : null
        }`}
      >
        {this.value && this.value > 99
          ? '99+'
          : this.value <= 0
          ? null
          : this.value}
        {}
      </span>
    );
  }
}

// packages/sources/react/src/components/VtmnBadge/VtmnBadge.tsx
import * as React from 'react';
import '@vtmn/css-badge';
import { VtmnBadgeVariant } from './types';

export interface VtmnBadgeProps extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * The variant of the badge.
   * @default 'default'
   */
  variant?: VtmnBadgeVariant;

  /**
   * The value of the badge.
   * @default null
   */
  value?: number;
}

export const VtmnBadge = ({
  variant = 'default',
  value,
  className,
  ...props
}: VtmnBadgeProps) => {
  return (
    <span
      className={`vtmn-badge vtmn-badge_variant--${variant} ${
        !value && value !== 0 ? 'vtmn-badge_size--without-value' : ''
      } ${className ? className : ''}`}
      {...props}>
      {value && value > 99 ? '99+' : value}
    </span>
  );
};

export default React.memo(VtmnBadge);
