// packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToast.svelte
<script>
  import { vtmnToastStore } from './vtmnToast';
  import { VtmnButton } from '../../';
</script>

{#each $vtmnToastStore as toast, index}
  <div
    class="vtmn-toast "
    class:show={toast.show}
    class:vtmn-toast--with-icon-info={toast.withIcon}
    role="status"
    style={`--toast-position:${index * 80}px`}
  >
    <div class="vtmn-toast_content">{toast.content}</div>
    {#if toast.withCloseButton}
      <VtmnButton
        on:click={() => vtmnToastStore.close(toast)}
        aria-label="Close alert"
        variant="ghost-reversed"
        size="small"
        iconAlone="close-line"
      />
    {/if}
  </div>
{/each}

<style>
  @import '@vtmn/css-toast';
  .vtmn-toast {
    transform: translate(50%, calc(-50% - var(--toast-position)));
  }
</style>

// packages/sources/react/src/components/overlays/VtmnToast/VtmnToast.tsx
import * as React from 'react';
import '@vtmn/css-alert/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton';

export interface VtmnToastProps
  extends React.ComponentPropsWithoutRef<'dialog'> {
  /**
   * The toast's content
   */
  content: string;

  /**
   * Whether there is an info icon
   */
  withIcon?: boolean;

  /**
   * Whether there is a close button
   */
  withCloseButton?: boolean;

  /**
   * The alert callback close function
   * @type {function}
   */
  onClose?: (event: React.MouseEvent | undefined) => void;
}

export const VtmnToast = ({
  content = '',
  withIcon = false,
  withCloseButton = false,
  onClose,
  className,
}: VtmnToastProps) => {
  return (
    <div
      role="status"
      className={clsx(
        'vtmn-toast',
        'show',
        withIcon && 'vtmn-toast--with-icon-info',
        className,
      )}
      onClick={onClose}
    >
      <div className="vtmn-toast_content">{content}</div>
      {onClose && withCloseButton && (
        <VtmnButton
          size="small"
          variant="ghost-reversed"
          iconAlone="close-line"
          aria-label="Close toast"
          onClick={onClose}
        ></VtmnButton>
      )}
    </div>
  );
};

const MemoVtmnToast = React.memo(VtmnToast);

MemoVtmnToast.displayName = 'VtmnToast';

export default MemoVtmnToast;
