// packages/sources/web-components/src/vtmn-button/vtmn-button.tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'vtmn-button',
  styleUrl: 'vtmn-button.pcss',
  shadow: true,
})
export class VtmnButton {
  @Prop() variant:
    | 'primary'
    | 'primary-reversed'
    | 'secondary'
    | 'secondary-reversed'
    | 'ghost'
    | 'conversion' = 'primary';

  @Prop() size: 'small' | 'medium' | 'large' | 'stretched' = 'medium';

  render() {
    return (
      <button
        class={`vtmn-btn vtmn-btn_variant--${this.variant} vtmn-btn_size--${this.size}`}
        type="button">
        <slot></slot>
      </button>
    );
  }
}

// packages/sources/vue/src/components/button/VtmnButton.vue
<script lang="ts">
import '@vtmn/css-button/dist/index.css';
import { reactive, computed, defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnButton',
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: (val: string) =>
        [
          'primary',
          'primary-reversed',
          'secondary',
          'secondary-reversed',
          'ghost',
          'conversion',
        ].includes(val),
    },
    size: {
      type: String,
      default: 'medium',
      validator: (val: string) =>
        ['small', 'medium', 'large', 'stretched'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-btn': true,
        [`vtmn-btn_variant--${props.variant}`]: true,
        [`vtmn-btn_size--${props.size}`]: true,
      })),
    };
  },
});
</script>

<template>
  <button type="button" :class="classes">
    <slot></slot>
  </button>
</template>
