// packages/sources/react/src/components/structure/VtmnDivider/VtmnDivider.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-divider/dist/index-with-vars.css';
import { VtmnDividerOrientation, VtmnDividerTextPosition } from './types';

export interface VtmnDividerProps
  extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The orientation of the divider.
   * @defaultValue 'horizontal'
   */
  orientation?: VtmnDividerOrientation;

  /**
   * The position of the text inside the divider.
   * @defaultValue 'start'
   */
  textPosition?: VtmnDividerTextPosition;

  /**
   * The id of divider label.
   * @defaultValue undefined
   */
  labelId?: string;
}

export const VtmnDivider = ({
  orientation = 'horizontal',
  textPosition = 'start',
  children,
  className,
  labelId,
  ...props
}: VtmnDividerProps) => {
  return (
    <div
      className={clsx(
        'vtmn-divider',
        `vtmn-divider_orientation--${orientation}`,
        children && `vtmn-divider_text-position--${textPosition}`,
        className,
      )}
      {...props}
      role="separator"
      aria-orientation={orientation}
      aria-labelledby={labelId ? labelId : undefined}
    >
      {children ? (
        <span id={labelId ? labelId : undefined}>{children}</span>
      ) : null}
    </div>
  );
};

const MemoVtmnDivider = React.memo(VtmnDivider);

MemoVtmnDivider.displayName = 'VtmnDivider';

export default MemoVtmnDivider;

// packages/sources/svelte/src/components/structure/VtmnDivider/VtmnDivider.svelte
<script>
  import { cn } from '../../../utils/classnames';

  import {
    VTMN_DIVIDER_ORIENTATION,
    VTMN_DIVIDER_TEXT_POSITION,
  } from './enums';

  /**
   * @type {string} Orientation of the divider
   */
  export let orientation = VTMN_DIVIDER_ORIENTATION.HORIZONTAL;

  /**
   * @type {string} Position of the text
   */
  export let textPosition = VTMN_DIVIDER_TEXT_POSITION.START;

  /**
   * @type {string} Id of the label
   */
  export let labelId;

  let className = undefined;

  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-divider',
    `vtmn-divider_orientation--${orientation}`,
    $$restProps['slot'] && `vtmn-divider_text-position--${textPosition}`,
    className,
  );
</script>

<div
  class={componentClass}
  role="separator"
  aria-orientation={orientation}
  aria-labelledby={labelId}
  {...$$restProps}
>
  {#if $$restProps['slot'] !== ''}
    <span id={labelId}>
      <slot />
    </span>
  {/if}
</div>

<style>
  @import '@vtmn/css-divider';
</style>
