// packages/sources/vue/src/components/overlays/VtmnPopover/VtmnPopover.vue
<script lang="ts">
import '@vtmn/css-popover/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';
import { VtmnPopoverPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnPopover',
  inheritAttrs: false,
  props: {
    id: {
      type: String as PropType<string>,
      required: true,
    },
    position: {
      type: String as PropType<VtmnPopoverPosition>,
      default: 'top',
      validator: (val: VtmnPopoverPosition) =>
        [
          'top-left',
          'top',
          'top-right',
          'right',
          'bottom-right',
          'bottom',
          'bottom-left',
          'left',
        ].includes(val),
    },
    title: {
      type: String as PropType<string>,
    },
    body: {
      type: String as PropType<string>,
    },
  },
});
</script>

<template>
  <div
    class="vtmn-popover"
    :data-position="position"
    :aria-describedby="id"
    :aria-labelledby="id + '-title'"
    tabindex="0"
    v-bind="$attrs"
  >
    <slot />

    <div :id="id" role="dialog">
      <p :id="id + '-title'" class="vtmn-popover_title" role="heading">
        {{ title }}
      </p>
      <p class="vtmn-popover_text">{{ body }}</p>
    </div>
  </div>
</template>

// packages/sources/react/src/components/overlays/VtmnPopover/VtmnPopover.tsx
import '@vtmn/css-popover/dist/index-with-vars.css';
import * as React from 'react';
import { VtmnPopoverPosition } from './types';

export interface VtmnPopoverProps
  extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * ID of the popover
   * @type {string}
   */
  identifier: string;

  /**
   * The position of the popover.
   * @defaultValue 'top'
   */
  position?: VtmnPopoverPosition;

  /**
   * The title of the popover.
   */
  title?: string;

  /**
   * The text of the popover.
   */
  body?: string;
}

export const VtmnPopover = ({
  identifier,
  position = 'top',
  title,
  body,
  children,
  ...props
}: VtmnPopoverProps) => {
  return (
    <div
      className="vtmn-popover"
      data-position={position}
      aria-describedby={identifier}
      aria-labelledby={`${identifier}-title`}
      tabIndex={0}
      {...props}
    >
      {children}

      <div id={identifier} role="dialog">
        <p
          className="vtmn-popover_title"
          id={`${identifier}-title`}
          role="heading"
        >
          {title}
        </p>
        <p className="vtmn-popover_text">{body}</p>
      </div>
    </div>
  );
};

const MemoVtmnPopover = React.memo(VtmnPopover);

MemoVtmnPopover.displayName = 'VtmnPopover';

export default MemoVtmnPopover;
