// packages/sources/vue/src/components/navigation/VtmnNavbar/VtmnNavbar.vue
<script lang="ts">
import '@vtmn/css-navbar/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnNavbar',
  components: {},
  props: {},
});
</script>

<template>
  <nav class="vtmn-navbar" aria-label="navbar" v-bind="$attrs">
    <div v-if="$slots['left-nav']" class="vtmn-navbar_left-navigation">
      <slot name="left-nav" />
    </div>

    <div v-if="$slots['logo']" class="vtmn-navbar_logo">
      <slot name="logo" />
    </div>

    <div v-if="$slots['middle-area']" class="vtmn-navbar_middle-area">
      <slot name="middle-area" />
    </div>

    <div v-if="$slots['right-nav']" class="vtmn-navbar_right-navigation">
      <slot name="right-nav" />
    </div>
  </nav>
</template>

// packages/sources/react/src/components/navigation/VtmnNavbar/VtmnNavbar.tsx
import * as React from 'react';
import '@vtmn/css-navbar/dist/index-with-vars.css';

export interface VtmnNavbarProps extends React.ComponentPropsWithoutRef<'nav'> {
  /**
   * The left navigation of the navbar.
   * @defaultValue undefined
   */
  leftNav?: React.ReactNode;

  /**
   * The logo of the navbar.
   * @defaultValue undefined
   */
  logo?: React.ReactNode;

  /**
   * The middle area of the navbar.
   * @defaultValue undefined
   */
  middleArea?: React.ReactNode;

  /**
   * The right navigation of the navbar.
   * @defaultValue undefined
   */
  rightNav?: React.ReactNode;
}

export const VtmnNavbar = ({
  leftNav,
  logo,
  middleArea,
  rightNav,
}: VtmnNavbarProps) => {
  return (
    <nav className="vtmn-navbar" aria-label="navbar">
      {leftNav && <div className="navbar_left-navigation">{leftNav}</div>}
      {logo && <div className="navbar_logo">{logo}</div>}
      {middleArea && <div className="navbar_middle-area">{middleArea}</div>}
      {rightNav && <div className="navbar_right-navigation">{rightNav}</div>}
    </nav>
  );
};

const MemoVtmnNavbar = React.memo(VtmnNavbar);

MemoVtmnNavbar.displayName = 'VtmnNavbar';

export default MemoVtmnNavbar;
