// packages/sources/svelte/src/components/VtmnLink.svelte
<script>
  import '@vtmn/css-link';

  /**
   * The size of the link.
   * @type {string}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Whether link is standalone or not.
   * @type {boolean}
   * @default false
   */
  export let standalone = false;

  /**
   * Whether link has an icon or not.
   * @type {boolean}
   * @default false
   */
  export let iconAlong = false;
</script>

<a
  class={[
    'vtmn-link',
    `vtmn-link_size--${size}`,
    standalone && 'vtmn-link--standalone',
    standalone && iconAlong && 'vtmn-link--icon-along',
  ]
    .filter(Boolean)
    .join(' ')}
  {...$$props}
>
  <slot />
</a>

// packages/sources/react/src/components/VtmnLink/VtmnLink.tsx
import * as React from 'react';
import clsx from 'clsx';

import '@vtmn/css-link/dist/index-with-vars.css';
import { VtmnLinkSize } from './types';

export interface VtmnLinkProps extends React.ComponentPropsWithoutRef<'a'> {
  /**
   * The size of the link.
   * @default 'medium'
   */
  size?: VtmnLinkSize;

  /**
   * Whether link is standalone or not.
   * @type {boolean}
   * @default false
   */
  standalone?: boolean;

  /**
   * Whether link has an icon or not.
   * @type {boolean}
   * @default false
   */
  iconAlong?: boolean;
}

export const VtmnLink = ({
  iconAlong = false,
  standalone = false,
  size = 'medium',
  children,
  className,
  ...props
}: VtmnLinkProps) => {
  return (
    <a
      className={clsx(
        'vtmn-link',
        `vtmn-link_size--${size}`,
        { 'vtmn-link--standalone': standalone },
        { 'vtmn-link--icon-along': standalone && iconAlong },
        className,
      )}
      {...props}>
      {children}
    </a>
  );
};

export default React.memo(VtmnLink);
