// packages/sources/vue/src/components/indicators/VtmnPrice/VtmnPrice.vue
<script lang="ts">
import '@vtmn/css-price/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnPriceSize, VtmnPriceVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnPrice',
  inheritAttrs: false,
  props: {
    variant: {
      type: String as PropType<VtmnPriceVariant>,
      default: 'primary',
      validator: (val: VtmnPriceVariant) =>
        ['default', 'accent', 'alert', 'strikethrough'].includes(val),
    },
    size: {
      type: String as PropType<VtmnPriceSize>,
      default: 'medium',
      validator: (val: VtmnPriceSize) =>
        ['xsmall', 'small', 'medium', 'large'].includes(val),
    },
    noPadding: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
      classes: computed(() => ({
        'vtmn-price': true,
        [`vtmn-price_variant--${props.variant}`]: props.variant,
        [`vtmn-price_size--${props.size}`]: true,
        'vtmn-price--no-padding': props.noPadding,
      })),
    };
  },
});
</script>

<template>
  <span :class="classes" v-bind="$attrs"><slot /></span>
</template>

// packages/sources/react/src/components/indicators/VtmnPrice/VtmnPrice.tsx
import * as React from 'react';
import '@vtmn/css-price/dist/index-with-vars.css';
import { VtmnPriceVariant, VtmnPriceSize } from './types';
import clsx from 'clsx';

export interface VtmnPriceProps extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * The variant of the price.
   * @defaultValue 'default'
   */
  variant?: VtmnPriceVariant;

  /**
   * The size of the price.
   * @defaultValue 'medium'
   */
  size?: VtmnPriceSize;

  /**
   * No padding on the price.
   * @defaultValue false
   */
  noPadding?: boolean;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnPrice = React.forwardRef<HTMLButtonElement, VtmnPriceProps>(
  (
    {
      variant = 'default',
      size = 'medium',
      noPadding = false,
      children,
      className,
      ...props
    },
    ref,
  ) => {
    return (
      <span
        ref={ref}
        className={clsx(
          `vtmn-price vtmn-price_variant--${variant} vtmn-price_size--${size}`,
          noPadding && 'vtmn-price--no-padding',
          className ? className : '',
        )}
        {...props}
      >
        {children}
      </span>
    );
  },
);

const MemoVtmnPrice = React.memo(VtmnPrice);

MemoVtmnPrice.displayName = 'VtmnPrice';

export default MemoVtmnPrice;
