// packages/sources/svelte/src/components/indicators/VtmnBadge/VtmnBadge.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VtmnBadgeVariant } from './enums';
  /**
   * The value of the badge
   * @type {number}
   */
  export let value;

  /**
   * The value of the badge
   * @type {'default' | 'brand' | 'reversed' | 'accent' | 'alert'}
   */
  export let variant = VtmnBadgeVariant.DEFAULT;

  let className;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-badge',
    variant && `vtmn-badge_variant--${variant}`,
    className,
  );

  $: computedValue = value > 99 ? '99+' : value || '';
</script>

<span class={componentClass} {...$$restProps}>{computedValue}</span>

<style lang="css">
  @import '@vtmn/css-badge';
</style>

// packages/sources/vue/src/components/indicators/VtmnBadge/VtmnBadge.vue
<script lang="ts">
import '@vtmn/css-badge/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnBadgeVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnBadge',
  props: {
    variant: {
      type: String as PropType<VtmnBadgeVariant>,
      default: 'default',
      validator: (val: VtmnBadgeVariant) =>
        ['default', 'brand', 'reversed', 'accent', 'alert'].includes(val),
    },
    value: {
      type: Number,
      default: undefined,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'vtmn-badge': true,
        [`vtmn-badge_variant--${props.variant}`]: true,
      })),
    };
  },
});
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    {{ value > 99 ? '99+' : value }}
  </span>
</template>
