// packages/sources/react/src/components/indicators/VtmnBadge/VtmnBadge.tsx
import * as React from 'react';
import '@vtmn/css-badge/dist/index-with-vars.css';
import { VtmnBadgeVariant } from './types';

export interface VtmnBadgeProps extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * The variant of the badge.
   * @defaultValue 'default'
   */
  variant?: VtmnBadgeVariant;

  /**
   * The value of the badge.
   * @defaultValue undefined
   */
  value?: number;
}

export const VtmnBadge = ({
  variant = 'default',
  value,
  className,
  ...props
}: VtmnBadgeProps) => {
  return (
    <span
      className={`vtmn-badge vtmn-badge_variant--${variant} ${
        className ? className : ''
      }`}
      {...props}
    >
      {value && value > 99 ? '99+' : value ?? ''}
    </span>
  );
};

const MemoVtmnBadge = React.memo(VtmnBadge);

MemoVtmnBadge.displayName = 'VtmnBadge';

export default MemoVtmnBadge;

// packages/sources/vue/src/components/indicators/VtmnBadge/VtmnBadge.vue
<script lang="ts">
import '@vtmn/css-badge/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnBadgeVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnBadge',
  props: {
    variant: {
      type: String as PropType<VtmnBadgeVariant>,
      default: 'default',
      validator: (val: VtmnBadgeVariant) =>
        ['default', 'brand', 'reversed', 'accent', 'alert'].includes(val),
    },
    value: {
      type: Number,
      default: undefined,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'vtmn-badge': true,
        [`vtmn-badge_variant--${props.variant}`]: true,
      })),
    };
  },
});
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    {{ value > 99 ? '99+' : value }}
  </span>
</template>
