// packages/sources/react/src/components/selection-controls/VtmnQuantity/VtmnQuantity.tsx
import * as React from 'react';
import '@vtmn/css-quantity';
import clsx from 'clsx';
import { VtmnButton } from '../../actions/VtmnButton/VtmnButton';
import { VtmnQuantitySize } from './types';

export interface VtmnQuantityProps
  extends Omit<React.ComponentPropsWithoutRef<'div'>, 'onChange'> {
  /**
   * The id of the quantity.
   * @type {string}
   */
  id: string;

  /**
   * The label attached to the quantity.
   * @type {string}
   * @defaultValue undefined
   */
  label?: string;

  /**
   * The value of the quantity.
   * @type {number}
   * @defaultValue 0
   */
  value?: number;

  /**
   * The step applied to the value of the quantity.
   * @type {number}
   * @defaultValue 1
   */
  step?: number;

  /**
   * The size of the quantity.
   * @defaultValue 'medium'
   */
  size?: VtmnQuantitySize;

  /**
   * Disabled state of the quantity.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;

  /**
   * Displays the quantity at 100% of its parent's width
   * @type {boolean}
   * @defaultValue false
   */
  fullWidth?: boolean;

  /**
   * The minimum value of the quantity.
   * @type {number}
   * @defaultValue 0
   */
  min?: number;

  /**
   * The minimum value of the quantity.
   * @type {number}
   * @defaultValue Infinity
   */
  max?: number;

  /**
   * The error to display when value is out of bounds.
   * @type {string}
   * @defaultValue undefined
   */
  error?: string;

  /**
   * Called when quantity's value has changed
   * @type {void}
   * @defaultValue undefined
   */
  onChange?: (newQuantity: number, action: string) => void;
}

export const VtmnQuantity = React.forwardRef<
  HTMLInputElement,
  VtmnQuantityProps
>(
  (
    {
      id,
      value = 0,
      step = 1,
      size = 'medium',
      label = undefined,
      disabled = false,
      fullWidth = false,
      min = 0,
      max = Infinity,
      error = undefined,
      onChange = undefined,
      className,
      ...props
    }: VtmnQuantityProps,
    ref,
  ) => {
    const [quantity, setQuantity] = React.useState(value);

    return (
      <div
        className={clsx(
          'vtmn-quantity',
          `vtmn-quantity_size--${size}`,
          { 'vtmn-quantity--full-width': fullWidth },
          className,
        )}
        {...props}
      >
        {label && <label htmlFor={id}>{label}</label>}

        <div className="vtmn-quantity_content">
          <VtmnButton
            variant="secondary"
            disabled={disabled || quantity <= min}
            iconAlone={'subtract-fill'}
            onClick={() =>
              setQuantity((oldQuantity) => {
                const newQuantity = Math.max(min, oldQuantity - step);

                onChange && onChange(newQuantity, 'subtract');

                return newQuantity;
              })
            }
            size={size}
            aria-label="subtract"
          />
          <input
            type="number"
            ref={ref}
            disabled={disabled}
            id={id}
            min={min}
            max={max}
            step={step}
            value={quantity}
            aria-describedby={`quantity-helper-${id}`}
            onChange={(event) => {
              const newQuantity = isNaN(event.target.valueAsNumber)
                ? min
                : event.target.valueAsNumber;

              onChange && onChange(newQuantity, 'edit');

              setQuantity(newQuantity);
            }}
            aria-invalid={error ? true : undefined}
          />
          <VtmnButton
            variant="secondary"
            disabled={disabled || quantity >= max}
            iconAlone={'add-fill'}
            size={size}
            onClick={() =>
              setQuantity((oldQuantity) => {
                const newQuantity = Math.min(max, oldQuantity + step);

                onChange && onChange(newQuantity, 'add');

                return newQuantity;
              })
            }
            aria-label="add"
          />
        </div>

        {error && (
          <p id={`quantity-helper-${id}`} className="vtmn-quantity_error-text">
            {error}
          </p>
        )}
      </div>
    );
  },
);

const MemoVtmnQuantity = React.memo(VtmnQuantity);

MemoVtmnQuantity.displayName = 'VtmnQuantity';

export default MemoVtmnQuantity;

// packages/sources/svelte/src/components/selection-controls/VtmnQuantity/VtmnQuantity.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { cn } from '../../../utils/classnames';
  import VtmnButton from '../../actions/VtmnButton/VtmnButton.svelte';

  /**
   * @type {string} id of the input
   */
  export let id;

  /**
   * @type {string} label displayed for the input
   */
  export let label;

  /**
   * @type {number} current value of the input
   */
  export let value = 0;

  /**
   * @type {boolean} disable the input
   */
  export let disabled = false;

  /**
   * @type {boolean} displays the quantity at 100% of its parent's width
   */
  export let fullWidth = false;

  /**
   * @type {string} error text displayed under the input
   */
  export let error = undefined;

  /**
   * @type {number} minimum value of the input
   */
  export let min = -Infinity;

  /**
   * @type {number} maximum value of the input
   */
  export let max = Infinity;

  /**
   * @type {number} step of the input. Will be add on the value when subtract or add event.
   * @default 1
   */
  export let step = 1;

  /**
   * The size of the quantity.
   * @type {'small' | 'medium'}
   * @defaultValue 'medium'
   */
  export let size = 'medium';

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  const dispatch = createEventDispatcher();
  const handleClickSubtract = () => {
    value -= step;
    dispatch('subtract', value);
    dispatch('change', { value, action: 'subtract' });
  };
  const handleClickAdd = () => {
    value += step;
    dispatch('add', value);
    dispatch('change', { value, action: 'add' });
  };

  let disabledMin, disabledMax;
  $: {
    disabledMin = value <= min;
    disabledMax = value >= max;
  }

  $: componentClass = cn(
    'vtmn-quantity',
    size && `vtmn-quantity_size--${size}`,
    fullWidth && 'vtmn-quantity--full-width',
    className,
  );
</script>

<div class={componentClass}>
  <label aria-disabled={disabled} for={id}>{label}</label>
  <div aria-disabled={disabled} class="vtmn-quantity_content">
    <VtmnButton
      on:click={handleClickSubtract}
      disabled={disabled || disabledMin}
      variant="secondary"
      iconAlone="subtract-line"
      aria-label="subtract"
      {size}
    />
    <input
      type="number"
      bind:value
      {id}
      {disabled}
      {min}
      {max}
      {step}
      aria-invalid={error ? true : undefined}
      aria-describedby={error ? `quantity-helper-${id}` : undefined}
      on:change
    />
    <VtmnButton
      on:click={handleClickAdd}
      disabled={disabled || disabledMax}
      variant="secondary"
      iconAlone="add-line"
      aria-label="add"
      {size}
    />
  </div>
  {#if error}
    <p id={`quantity-helper-${id}`} class="vtmn-quantity_error-text">
      {error}
    </p>
  {/if}
</div>

<style>
  @import '@vtmn/css-quantity';
</style>
