// packages/sources/svelte/src/components/actions/VtmnDropdownItem/VtmnDropdownItem.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.svelte';
  import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.svelte';

  /**
   * @type {string} if of the item
   * @requires
   */
  export let id;

  /**
   * @type {object} Value of the dropdown item
   * @requires
   */
  export let value;

  /**
   * @type {object[]} Array of selected items
   * @requires
   */
  export let group;

  /**
   * @type {boolean} If the dropdown item are checked
   */
  export let checked = false;

  /**
   * @type {boolean} Apply divider on the item
   * @defaultValue false
   */
  export let divider = false;

  /**
   * @type {string} Icon of menu item.
   */
  export let icon = undefined;
  /**
   * Custom classes to apply to the component.
   * @type {string} className
   */
  let className = undefined;

  export { className as class };
  $: componentClass = cn(className);

  const updateChekbox = (group) => (checked = group.indexOf(value) >= 0);

  const updateGroup = (checked) => {
    const index = group.indexOf(value);
    if (checked) {
      if (index < 0) {
        group.push(value);
        group = group;
      }
      return;
    }
    if (index >= 0) {
      group.splice(index, 1);
      group = group;
    }
  };

  $: group && updateChekbox(group);
  $: group && updateGroup(checked);
</script>

<input
  type="checkbox"
  {id}
  class={componentClass}
  bind:checked
  on:change
  {value}
  {...$$restProps}
/>

<label for={id}>
  {#if icon}
    <VtmnIcon value={icon} />
  {/if}

  <slot />
</label>

{#if divider}
  <VtmnDivider orientation="horizontal" role="separator" />
{/if}

<style lang="css">
  @import '@vtmn/css-dropdown';
</style>

// packages/sources/vue/src/components/actions/VtmnDropdownItem/VtmnDropdownItem.vue
<script lang="ts">
import '@vtmn/css-dropdown/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { defineComponent, PropType } from 'vue';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';
import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnDropdownItem',
  components: { VtmnIcon, VtmnDivider },
  props: {
    selected: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    divider: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    icon: {
      type: String as PropType<VitamixId>,
      default: null,
    },
  },
  emits: ['update:modelValue'],
  setup(_, { attrs, emit }) {
    const labelId = attrs['id'] ? String(attrs['id']) : undefined;

    const handleChange = (event: Event) => {
      if (event && event.target) {
        return emit(
          'update:modelValue',
          (event.target as HTMLInputElement).checked,
        );
      }
    };

    return {
      labelId,
      handleChange,
    };
  },
});
</script>

<template>
  <input
    type="checkbox"
    :cheched="selected"
    @change="handleChange"
    v-bind="$attrs"
  />
  <label :for="labelId">
    <VtmnIcon v-if="icon" :value="icon" aria-hidden="true" />
    <slot />
  </label>
  <VtmnDivider v-if="divider" orientation="horizontal" role="separator" />
</template>
