// packages/sources/svelte/src/components/Button.svelte
<script>
  import '@vtmn/css-button/dist/index.css';
  /**
   * The variant of the button.
   * @type {'primary' | 'primary-reversed' | 'secondary' | 'secondary-reversed' | 'ghost' | 'conversion'}
   * @default 'primary'
   */
  export let variant;
  /**
   * The size of the button.
   * @type {'small' | 'medium' | 'large' | 'stretched'}
   * @default 'medium'
   */
  export let size = 'medium';
</script>

<button
  type="button"
  class={['vtmn-btn', `vtmn-btn_variant--${variant}`, `vtmn-btn_size--${size}`].join(' ')}
  {...$$restProps}>
  <slot></slot>
</button>

// packages/sources/react/src/components/Button/Button.tsx
import * as React from 'react';
import '@vtmn/css-button';
import classNames from 'classnames';

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /**
   * That variant of the button.
   * @default 'primary'
   */
  variant?:
    | 'primary'
    | 'primary-reversed'
    | 'secondary'
    | 'secondary-reversed'
    | 'ghost'
    | 'conversion';
  /**
   * The size of the button.
   * @default 'medium'
   */
  size?: 'small' | 'medium' | 'large' | 'stretched';
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'medium',
  children,
  className,
  disabled,
  ...props
}) => (
  <button
    className={classNames(className, 'vtmn-btn', {
      [`vtmn-btn_variant--${variant}`]: variant,
      [`vtmn-btn_size--${size}`]: size && size !== 'medium',
      'vtmn-btn_disabled': disabled,
    })}
    disabled={disabled}
    {...props}>
    {children}
  </button>
);

export default React.memo(Button);
