// packages/sources/svelte/src/components/structure/VtmnCard/VtmnCard.svelte
<script>
  import { VTMN_CARD_VARIANT } from './enums';
  import { cn } from '../../../utils/classnames';

  /**
   * @type {string} title of the card
   */
  export let title = undefined;

  /**
   * @type {'top-image' | 'side-image' | 'full-image' } variant of the card
   */
  export let variant = VTMN_CARD_VARIANT.TOP_IMAGE;

  /**
   * @type {boolean} display image on full screen.
   * Only for variant 'top-image'
   */
  export let fullImage = false;

  /**
   * @type {boolean} display the content with opaque style
   * Only for variant 'full-image'
   */
  export let contentOpaque = false;

  /**
   * @type {1|2|3|4|5|6} Heading level of card title
   * @default 2
   */
  export let headingLevel = 2;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  const Heading = `h${headingLevel}`;

  $: componentClass = cn(
    'vtmn-card',
    variant && `vtmn-card_variant--${variant}`,
    className,
  );

  $: componentImageClass = cn(
    'vtmn-card_image',
    variant === VTMN_CARD_VARIANT.TOP_IMAGE &&
      fullImage &&
      'vtmn-card_image--full',
  );

  $: componentContentClass = cn(
    'vtmn-card_content',
    variant === VTMN_CARD_VARIANT.FULL_IMAGE &&
      contentOpaque &&
      'vtmn-card_content--opaque',
  );
</script>

<div class={componentClass}>
  {#if $$slots.img}
    <div class={componentImageClass}>
      <slot name="img" />
    </div>
  {/if}
  <div class={componentContentClass}>
    {#if title}
      <svelte:element this={Heading} class="vtmn-card_content--title">
        {title}
      </svelte:element>
    {/if}
    {#if $$slots.content}
      <span class="vtmn-card_content--body">
        <slot name="content" />
      </span>
    {/if}
    <slot name="actions" />
  </div>
</div>

<style>
  @import '@vtmn/css-card';
</style>

// packages/sources/vue/src/components/structure/VtmnCard/VtmnCard.vue
<script lang="ts">
import '@vtmn/css-card/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnCardVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnCard',
  inheritAttrs: false,
  props: {
    title: {
      type: String as PropType<string>,
      default: 'Card title',
    },
    variant: {
      type: String as PropType<VtmnCardVariant>,
      default: 'top-image',
      validator: (val: VtmnCardVariant) =>
        ['top-image', 'side-image', 'full-image'].includes(val),
    },
    fullImage: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    contentOpaque: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    headingLevel: {
      type: Number as PropType<number>,
      default: 2,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      componentClasses: computed(() => ({
        'vtmn-card': true,
        [`vtmn-card_variant--${props.variant}`]: props.variant,
      })),

      componentImageClasses: computed(() => ({
        'vtmn-card_image': true,
        'vtmn-card_image--full':
          props.variant === 'top-image' && props.fullImage,
      })),

      componentContentClasses: computed(() => ({
        'vtmn-card_content': true,
        'vtmn-card_content--opaque':
          props.variant === 'full-image' && props.contentOpaque,
      })),

      Heading: computed(() => {
        return props.headingLevel >= 0 && props.headingLevel <= 6
          ? `h${props.headingLevel}`
          : 'h2';
      }),
    };
  },
});
</script>

<template>
  <div :class="componentClasses" v-bind="$attrs">
    <div v-if="$slots['img']" :class="componentImageClasses">
      <slot name="img" />
    </div>
    <div :class="componentContentClasses">
      <component
        :is="Heading"
        v-if="$props.title"
        class="vtmn-card_content--title"
      >
        {{ $props.title }}
      </component>

      <template v-if="$slots['content']">
        <span class="vtmn-card_content--body">
          <slot name="content" />
        </span>
      </template>

      <template v-if="$slots['actions']">
        <slot name="actions" />
      </template>
    </div>
  </div>
</template>
