// packages/sources/vue/src/components/actions/VtmnButton/VtmnButton.vue
<script lang="ts">
import '@vtmn/css-button/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnButtonSize, VtmnButtonVariant } from './types';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnButton',
  components: { VtmnIcon },
  props: {
    variant: {
      type: String as PropType<VtmnButtonVariant>,
      default: 'primary',
      validator: (val: VtmnButtonVariant) =>
        [
          'primary',
          'primary-reversed',
          'secondary',
          'tertiary',
          'ghost',
          'ghost-reversed',
          'conversion',
        ].includes(val),
    },
    size: {
      type: String as PropType<VtmnButtonSize>,
      default: 'medium',
      validator: (val: VtmnButtonSize) =>
        ['small', 'medium', 'large', 'stretched'].includes(val),
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    iconLeft: {
      type: String as PropType<VitamixId>,
      default: null,
    },
    iconRight: {
      type: String as PropType<VitamixId>,
      default: null,
    },
    iconAlone: {
      type: String as PropType<VitamixId>,
      default: null,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit'
      },
      classes: computed(() => ({
        'vtmn-btn': true,
        [`vtmn-btn_variant--${props.variant}`]: true,
        [`vtmn-btn_size--${props.size}`]: true,
        'vtmn-btn--icon-left': !props.iconAlone && props.iconLeft,
        'vtmn-btn--icon-right': !props.iconAlone && props.iconRight,
        'vtmn-btn--icon-alone': props.iconAlone,
      })),
    };
  },
});
</script>

<template>
  <button :class="classes" v-bind="$attrs" :disabled="disabled">
    <VtmnIcon v-if="!iconAlone && iconLeft" :value="iconLeft" :style="styleObject" />
    <VtmnIcon v-if="iconAlone" :value="iconAlone" :style="styleObject" />
      <slot v-if="!iconAlone" />
    <VtmnIcon v-if="!iconAlone && iconRight" :value="iconRight" :style="styleObject" />
  </button>
</template>

// packages/sources/react/src/components/actions/VtmnButton/VtmnButton.tsx
import * as React from 'react';
import '@vtmn/css-button/dist/index-with-vars.css';
import { VtmnButtonVariant, VtmnButtonSize } from './types';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';

export interface VtmnButtonProps
  extends React.ComponentPropsWithoutRef<'button'> {
  /**
   * The variant of the button.
   * @defaultValue 'primary'
   */
  variant?: VtmnButtonVariant;
  /**
   * The size of the button.
   * @defaultValue 'medium'
   */
  size?: VtmnButtonSize;

  /**
   * Icon to display on the left hand side of button.
   * @type {VitamixId}
   * @defaultValue undefined
   */
  iconLeft?: VitamixId;

  /**
   * Icon to display on the right hand side of button.
   * @type {VitamixId}
   * @defaultValue undefined
   */
  iconRight?: VitamixId;

  /**
   * Icon to display when it is a button with icon only.
   * @type {VitamixId}
   * @defaultValue undefined
   */
  iconAlone?: VitamixId;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnButton = React.forwardRef<HTMLButtonElement, VtmnButtonProps>(
  (
    {
      variant = 'primary',
      size = 'medium',
      iconLeft,
      iconRight,
      iconAlone,
      children,
      className,
      ...props
    },
    ref,
  ) => {
    return (
      <button
        ref={ref}
        className={`vtmn-btn vtmn-btn_variant--${variant} vtmn-btn_size--${size} ${
          className ? className : ''
        } ${!iconAlone && iconLeft ? 'vtmn-btn--icon-left' : ''} ${
          !iconAlone && iconRight ? 'vtmn-btn--icon-right' : ''
        } ${iconAlone ? 'vtmn-btn--icon-alone' : ''}`}
        {...props}
      >
        {!iconAlone && iconLeft && (
          <VtmnIcon
            value={iconLeft}
            style={{ color: 'inherit', fontSize: 'inherit' }}
          />
        )}
        {iconAlone ? (
          <VtmnIcon
            value={iconAlone}
            style={{ color: 'inherit', fontSize: 'inherit' }}
          />
        ) : (
          children
        )}
        {!iconAlone && iconRight && (
          <VtmnIcon
            value={iconRight}
            style={{ color: 'inherit', fontSize: 'inherit' }}
          />
        )}
      </button>
    );
  },
);

const MemoVtmnButton = React.memo(VtmnButton);

MemoVtmnButton.displayName = 'VtmnButton';

export default MemoVtmnButton;
