// packages/sources/react/src/components/actions/VtmnLink/VtmnLink.tsx
import * as React from 'react';
import '@vtmn/css-link/dist/index-with-vars.css';
import clsx from 'clsx';
import { VtmnLinkSize } from './types';

export interface VtmnLinkProps extends React.ComponentPropsWithoutRef<'a'> {
  /**
   * The size of the link.
   * @defaultValue 'medium'
   */
  size?: VtmnLinkSize;

  /**
   * Whether link is standalone or not.
   * @type {boolean}
   * @defaultValue false
   */
  standalone?: boolean;

  /**
   * The target attribute of the link.
   * @type {string}
   * @defaultValue undefined
   * @requires
   */
  target: string;

  /**
   * The rel attribute of the link.
   * @type {string}
   * @defaultValue undefined
   */
  rel?: string;

  /**
   * Whether link is reversed or not.
   * @type {boolean}
   * @defaultValue false
   */
  reversed?: boolean;

  /**
   * Whether link has an icon or not.
   * @type {boolean}
   * @defaultValue false
   */
  iconAlong?: boolean;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children: React.ReactNode;
}

export const VtmnLink = ({
  iconAlong = false,
  standalone = false,
  reversed = false,
  target,
  rel = '',
  size = 'medium',
  children,
  className,
  ...props
}: VtmnLinkProps) => {
  return (
    <a
      target={target}
      rel={
        target === '_blank'
          ? Array.from(
              new Set(rel.split(' ')).add('noopener').add('noreferrer'),
            )
              .join(' ')
              .trim()
          : rel
      }
      className={clsx(
        'vtmn-link',
        `vtmn-link_size--${size}`,
        { 'vtmn-link--standalone': standalone },
        { 'vtmn-link--reversed': reversed },
        { 'vtmn-link--icon-along': standalone && iconAlong },
        className,
      )}
      {...props}
    >
      {children}
    </a>
  );
};

const MemoVtmnLink = React.memo(VtmnLink);

MemoVtmnLink.displayName = 'VtmnLink';

export default MemoVtmnLink;

// packages/sources/vue/src/components/actions/VtmnLink/VtmnLink.vue
<script lang="ts">
import '@vtmn/css-link/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnLinkSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnLink',
  props: {
    size: {
      type: String as PropType<VtmnLinkSize>,
      default: 'medium',
      validator: (val: VtmnLinkSize) =>
        ['small', 'medium', 'large'].includes(val),
    },
    standalone: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    reversed: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    iconAlong: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(props, { attrs }) {
    props = reactive(props);

    let computedRel = '';

    if (String(attrs['target']) === '_blank') {
      if (attrs['rel'] !== undefined) {
        computedRel = Array.from(
          new Set(String(attrs['rel']).split(' '))
            .add('noopener')
            .add('noreferrer'),
        )
          .join(' ')
          .trim();
      } else {
        computedRel = 'noopener noreferrer';
      }
    } else {
      computedRel = String(attrs['rel']);
    }

    return {
      classes: computed(() => ({
        'vtmn-link': true,
        [`vtmn-link_size--${props.size}`]: true,
        'vtmn-link--standalone': props.standalone,
        'vtmn-link--reversed': props.reversed,
        'vtmn-link--icon-along': props.iconAlong && props.standalone,
      })),
      computedRel,
    };
  },
});
</script>

<template>
  <a :rel="computedRel" :class="classes" v-bind="$attrs">
    <slot />
  </a>
</template>
