// packages/sources/vue/src/components/structure/VtmnSkeleton/VtmnSkeleton.vue
<script lang="ts">
import '@vtmn/css-skeleton/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnSkeletonShape } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnSkeleton',
  inheritAttrs: false,
  props: {
    width: {
      type: String as PropType<string>,
      default: '100%',
    },
    height: {
      type: String as PropType<string>,
    },
    shape: {
      type: String as PropType<VtmnSkeletonShape>,
      default: 'line',
      validator: (val: VtmnSkeletonShape) => ['line', 'avatar'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'vtmn-skeleton': true,
        [`vtmn-skeleton_${props.shape}`]: props.shape,
      })),
      styles: computed(() => ({
        width: props.width,
        height: props.height,
      })),
    };
  },
});
</script>

<template>
  <span :class="classes" :style="styles" v-bind="$attrs">
    <slot />
  </span>
</template>

// packages/sources/react/src/components/structure/VtmnSkeleton/VtmnSkeleton.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-skeleton/dist/index-with-vars.css';
import { VtmnSkeletonShape } from './types';

export interface VtmnSkeletonProps
  extends React.ComponentPropsWithoutRef<'span'> {
  /**
   * Width of the skeleton
   * @defaultValue 100%
   */
  width?: string;

  /**
   * Height of the skeleton
   */
  height?: string;

  /**
   * Define the type of shape.
   * @defaultValue 'line'
   */
  shape?: VtmnSkeletonShape;
}

export const VtmnSkeleton = ({
  width = '100%',
  height,
  shape = 'line',
  className,
  ...props
}: VtmnSkeletonProps) => {
  return (
    <span
      className={clsx('vtmn-skeleton', `vtmn-skeleton_${shape}`, className)}
      style={{ width, height }}
      {...props}
    ></span>
  );
};

const MemoVtmnSkeleton = React.memo(VtmnSkeleton);

MemoVtmnSkeleton.displayName = 'VtmnSkeleton';

export default MemoVtmnSkeleton;
