// packages/sources/react/src/components/VtmnRadio/VtmnRadio.tsx
import * as React from 'react';

import '@vtmn/css-radio-button';

export interface VtmnRadioProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * ID of the radio.
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the radio.
   * @type {string}
   * @default undefined
   */
  labelText?: string;

  /**
   * Name of the radio.
   * @type {string}
   * @default undefined
   */
  name?: string;

  /**
   * Disabled state of the radio.
   * @type {boolean}
   */
  disabled?: boolean;
}

export const VtmnRadio = ({
  identifier,
  labelText,
  name,
  disabled,
  ...props
}: VtmnRadioProps) => {
  return (
    <div>
      <input
        className="vtmn-radio-button"
        type="radio"
        id={identifier}
        name={name}
        disabled={disabled}
        {...props}
      />
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

export default React.memo(VtmnRadio);

// packages/sources/vue/src/components/VtmnRadio/VtmnRadio.vue
<script lang="ts">
import '@vtmn/css-radio-button/dist/index.css';
import { defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnRadio',
  props: {
    identifier: {
      type: String,
      default: null,
    },
    labelText: {
      type: String,
      default: null,
    },
    name: {
      type: String,
      default: null,
    },
    value: {
      type: String,
      default: null,
    },
    checked: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<template>
  <input
    class="vtmn-radio-button"
    type="radio"
    :id="this.identifier"
    :name="this.name"
    :value="this.value"
    :checked="this.checked"
    :disabled="this.disabled"
    v-bind="$attrs"
  />
  <label :for="this.identifier">{{ this.labelText }}</label>
</template>
