// packages/sources/vue/src/components/indicators/VtmnPrice/VtmnPrice.vue
<script lang="ts">
import '@vtmn/css-price/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';
import { VtmnPriceSize, VtmnPriceVariant } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnPrice',
  inheritAttrs: false,
  props: {
    variant: {
      type: String as PropType<VtmnPriceVariant>,
      default: 'primary',
      validator: (val: VtmnPriceVariant) =>
        ['default', 'accent', 'alert', 'strikethrough'].includes(val),
    },
    size: {
      type: String as PropType<VtmnPriceSize>,
      default: 'medium',
      validator: (val: VtmnPriceSize) =>
        ['xsmall', 'small', 'medium', 'large'].includes(val),
    },
    noPadding: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
      classes: computed(() => ({
        'vtmn-price': true,
        [`vtmn-price_variant--${props.variant}`]: props.variant,
        [`vtmn-price_size--${props.size}`]: true,
        'vtmn-price--no-padding': props.noPadding,
      })),
    };
  },
});
</script>

<template>
  <span :class="classes" v-bind="$attrs"><slot /></span>
</template>

// packages/sources/svelte/src/components/indicators/VtmnPrice/VtmnPrice.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VTMN_PRICE_VARIANT, VTMN_PRICE_SIZE } from './enums';

  /**
   * Size of the price
   * @type { 'xsmall' | 'small' | 'medium' | 'large' }
   * @defaultValue 'medium'
   */
  export let size = VTMN_PRICE_SIZE.MEDIUM;

  /**
   * Variant of the price
   * @type {'default' | 'accent' | 'alert' | 'strikethrough'}
   * @defaultValue 'default'
   */
  export let variant = VTMN_PRICE_VARIANT.DEFAULT;

  /**
   * No padding on the price
   * @type boolean
   * @defaultValue false
   */
  export let noPadding = false;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-price',
    size && `vtmn-price_size--${size}`,
    variant && `vtmn-price_variant--${variant}`,
    noPadding && 'vtmn-price--no-padding',
    className,
  );
</script>

<span class={componentClass} {...$$restProps}>
  <slot />
</span>

<style lang="css">
  @import '@vtmn/css-price';
</style>
