// packages/sources/vue/src/components/selection-controls/VtmnCheckbox/VtmnCheckbox.vue
<script lang="ts">
import '@vtmn/css-checkbox/dist/index-with-vars.css';
import { defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnCheckbox',
  props: {
    labelText: {
      type: String,
      default: null,
    },
    identifier: {
      type: String,
      default: null,
    },
    checked: {
      type: Boolean,
      default: false,
    },
    value: {
      type: String,
      default: null,
    },
    name: {
      type: String,
      default: null,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<template>
  <input
    class="vtmn-checkbox"
    type="checkbox"
    :checked="this.checked"
    :id="this.identifier"
    :name="this.name"
    :disabled="this.disabled"
    :value="this.value"
    v-bind="$attrs"
  />
  <label :for="this.identifier">{{ this.labelText }}</label>
</template>

// packages/sources/react/src/components/selection-controls/VtmnCheckbox/VtmnCheckbox.tsx
import * as React from 'react';
import '@vtmn/css-checkbox/dist/index-with-vars.css';

export interface VtmnCheckboxProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * The id of the checkbox.
   * @type {string}
   */
  identifier: string;

  /**
   * The label of the checkbox.
   * @type {string}
   * @defaultValue undefined
   */
  labelText?: string;

  /**
   * The checked state of the checkbox.
   * @type {boolean}
   * @defaultValue false
   */
  checked?: boolean;

  /**
   * The disabled state of the checkbox.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;
}

export const VtmnCheckbox = ({
  identifier,
  labelText,
  checked = false,
  disabled = false,
  ...props
}: VtmnCheckboxProps) => {
  return (
    <div>
      <input
        className="vtmn-checkbox"
        type="checkbox"
        id={identifier}
        checked={checked}
        disabled={disabled}
        {...props}
      />
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

const MemoVtmnCheckbox = React.memo(VtmnCheckbox);

MemoVtmnCheckbox.displayName = 'VtmnCheckbox';

export default MemoVtmnCheckbox;
