// packages/sources/svelte/src/components/navigation/VtmnNavbar/VtmnNavbar.svelte
<script>
  import { cn } from '../../../utils/classnames';

  /** @restProps { button } */

  /**
   * Logo anchor.
   *
   * @type {string} [logoHref]
   */
  export let logoHref = '#';

  let className = '';
  /**
   * Custom classes to apply to the component.
   *
   * @type {string}
   */
  export { className as class };

  $: componentClass = cn('vtmn-navbar', className);

  /**
   * Delete slot div from de DOM if slot doesn't exist.
   *
   * @param {'left-nav' | 'logo' | 'middle-area' | 'right-nav'} slotName
   * @returns {boolean} slotExists
   */
  const checkSlotExists = (slotName) => {
    return $$slots[slotName];
  };
</script>

<nav class={componentClass} aria-label="navbar" {...$$restProps}>
  {#if checkSlotExists('left-nav')}
    <div class="vtmn-navbar_left-navigation">
      <slot name="left-nav" />
    </div>
  {/if}

  {#if checkSlotExists('logo')}
    <div class="vtmn-navbar_right-navigation">
      <a class="vtmn-navbar_logo" href={logoHref}>
        <slot name="logo" />
      </a>
    </div>
  {/if}

  {#if checkSlotExists('middle-area')}
    <div class="vtmn-navbar_middle-area">
      <slot name="middle-area" />
    </div>
  {/if}

  {#if checkSlotExists('right-nav')}
    <div class="vtmn-navbar_right-navigation">
      <slot name="right-nav" />
    </div>
  {/if}
</nav>

<style lang="css">
  @import '@vtmn/css-navbar';
</style>

// packages/sources/vue/src/components/navigation/VtmnNavbar/VtmnNavbar.vue
<script lang="ts">
import '@vtmn/css-navbar/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnNavbar',
  components: {},
  props: {
    logoHref: {
      type: String as PropType<string>,
      default: '#',
    },
  },
});
</script>

<template>
  <nav class="vtmn-navbar" aria-label="navbar" v-bind="$attrs">
    <div v-if="$slots['left-nav']" class="vtmn-navbar_left-navigation">
      <slot name="left-nav" />
    </div>

    <a v-if="$slots['logo']" class="vtmn-navbar_logo" :href="logoHref">
      <slot name="logo" />
    </a>

    <div v-if="$slots['middle-area']" class="vtmn-navbar_middle-area">
      <slot name="middle-area" />
    </div>

    <div v-if="$slots['right-nav']" class="vtmn-navbar_right-navigation">
      <slot name="right-nav" />
    </div>
  </nav>
</template>
