// packages/sources/react/src/components/selection-controls/VtmnChip/VtmnChip.tsx
import * as React from 'react';
import clsx from 'clsx';
import '@vtmn/css-chip/dist/index-with-vars.css';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { VtmnChipSize, VtmnChipVariant } from './types';
import { VtmnIcon } from '../../../guidelines/iconography/VtmnIcon/VtmnIcon';
import { VtmnButton } from '../../actions/VtmnButton/VtmnButton';
import { VtmnBadge } from '../../indicators/VtmnBadge/VtmnBadge';

export interface VtmnChipProps extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * Called when clicking the chip
   * @type {React.MouseEventHandler}
   * @defaultValue undefined
   */
  onClick?: React.MouseEventHandler;

  /**
   * Called when the cross is clicked when using input variant
   * @type {React.MouseEventHandler}
   * @defaultValue undefined
   */
  onCancel?: React.MouseEventHandler;

  /**
   * The variant of the chip.
   * @defaultValue 'single-choice'
   */
  variant?: VtmnChipVariant;

  /**
   * The size of the chip.
   * @defaultValue 'medium'
   */
  size?: VtmnChipSize;

  /**
   * Disabled state of the chip.
   * @type {boolean}
   * @defaultValue false
   */
  disabled?: boolean;

  /**
   * Selected state of the chip.
   * @type {boolean}
   * @defaultValue false
   */
  selected?: boolean;

  /**
   * Icon to display on the chip
   * @type {VitamixId}
   * @defaultValue undefined
   */
  icon?: VitamixId;

  /**
   * Number to display in chip's badge
   * @type number
   * @defaultValue 0
   */
  badgeValue?: number;
}

export const VtmnChip = ({
  variant = 'single-choice',
  size = 'medium',
  disabled = false,
  selected = false,
  icon = undefined,
  badgeValue = 0,
  onClick,
  onCancel,
  children,
  className,
  ...props
}: VtmnChipProps) => {
  const isSelected = selected && ['single-choice', 'filter'].includes(variant);
  return (
    <div
      className={clsx(
        'vtmn-chip',
        `vtmn-chip_size--${size}`,
        `vtmn-chip_variant--${variant}`,
        disabled && 'vtmn-chip--disabled',
        isSelected && 'vtmn-chip--selected',
        className,
      )}
      role="button"
      aria-disabled={disabled}
      aria-pressed={isSelected && variant !== 'action'}
      onClick={(e) => {
        if (!disabled && onClick) {
          onClick(e);
        }
      }}
      {...props}
    >
      {icon && (variant === 'input' || variant === 'action') && (
        <VtmnIcon
          variant={selected && variant !== 'action' ? 'reversed' : 'default'}
          value={icon}
          aria-hidden="true"
        />
      )}

      {children}

      {variant == 'filter' && badgeValue != 0 && (
        <VtmnBadge variant="default" value={badgeValue} />
      )}

      {variant == 'input' && (
        <VtmnButton
          variant="ghost"
          iconAlone="close-line"
          disabled={disabled}
          size={size}
          onClick={(e) => {
            e.stopPropagation();
            onCancel?.(e);
          }}
        />
      )}
    </div>
  );
};

const MemoVtmnChip = React.memo(VtmnChip);

MemoVtmnChip.displayName = 'VtmnChip';

export default MemoVtmnChip;

// packages/sources/vue/src/components/selection-controls/VtmnChip/VtmnChip.vue
<script lang="ts">
import '@vtmn/css-chip/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VitamixId } from '@vtmn/icons/dist/vitamix/font/vitamix';
import { VtmnChipVariant, VtmnChipSize } from './types';
import { VtmnBadge, VtmnButton } from '../../index';
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnChip',
  inheritAttrs: false,
  components: { VtmnBadge, VtmnButton, VtmnIcon },
  props: {
    modelValue: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    variant: {
      type: String as PropType<VtmnChipVariant>,
      default: 'single-choice',
      validator: (val: VtmnChipVariant) =>
        ['single-choice', 'input', 'filter', 'action'].includes(val),
    },
    size: {
      type: String as PropType<VtmnChipSize>,
      default: 'medium',
      validator: (val: VtmnChipSize) => ['small', 'medium'].includes(val),
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    selected: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    icon: {
      type: String as PropType<VitamixId>,
      default: null,
    },
    badgeValue: {
      type: Number as PropType<number>,
      default: 0,
    },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    props = reactive(props);

    const handleChange = (event: Event) => {
      if (event && event.target) {
        return emit(
          'update:modelValue',
          (event.target as HTMLInputElement).checked,
        );
      }
    };

    return {
      styleObject: {
        color: 'inherit',
        fontSize: 'inherit',
      },
      classes: computed(() => ({
        'vtmn-chip': true,
        [`vtmn-chip_variant--${props.variant}`]: props.variant,
        [`vtmn-chip_size--${props.size}`]: props.size,
        ['vtmn-chip--selected']: props.selected && props.variant !== 'action',
        ['vtmn-chip--disabled']: props.disabled,
      })),
      handleChange,
    };
  },
});
</script>

<template>
  <div
    :class="classes"
    :value="modelValue"
    role="button"
    :aria-disabled="disabled"
    :aria-pressed="selected && variant !== 'action'"
  >
    <VtmnIcon
      v-if="(variant === 'input' || variant === 'action') && icon"
      :value="icon"
      :style="styleObject"
      aria-hidden="true"
    />
    <slot />
    <VtmnButton
      v-if="variant === 'input' && selected"
      :variant="'ghost-reversed'"
      :iconAlone="'close-line'"
      :size="size"
      :disabled="disabled"
      aria-label="Unselect the selection"
    />
    <VtmnBadge
      v-if="variant === 'filter' && badgeValue > 0"
      :value="badgeValue"
    />
  </div>
</template>
