// packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { isFloat } from '../../../utils/math';
  import { VTMN_RATING_SIZE } from './enum';
  import VtmnIcon from '../../../guidelines/iconography/VtmnIcon/VtmnIcon.svelte';

  /**
   * @type {string} name used on interactive mode to name the inputs
   * @required
   */
  export let name;

  /**
   * @type {boolean} use the emphasis mode. Only if readonly is true.
   * @default false
   */
  export let emphasis = false;

  /**
   * @type {string} size of the component
   * @default small
   */
  export let size = VTMN_RATING_SIZE.SMALL;

  /**
   * @type {boolean} disable the component
   * @default false
   */
  export let disabled = false;

  /**
   * @type {boolean} is readonly component
   * @default false
   */
  export let readonly = false;

  /**
   * @type {boolean} enable the compact mode. Only if readonly is true.
   * @default false
   */
  export let compact = false;

  /**
   * @type {number} rating to display on the component
   * @requires
   */
  export let value;

  /**
   * @type {boolean} display the rating value. Only if readonly is true.
   * default false
   */
  export let showValue = false;

  /**
   * @type {number} Comments displayed after the rating. Only if readonly is true.
   */
  export let comments = undefined;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn(
    'vtmn-rating',
    size && `vtmn-rating_size--${size}`,
    emphasis && 'vtmn-rating_variant--brand',
    className,
  );
  $: starsCnt = compact && readonly ? 1 : 5;

  const computeRatingFill = (currentRatingStar) => {
    if (starsCnt === 1) {
      return value === 0 ? 'line' : 'fill';
    }
    if (currentRatingStar <= value) {
      return 'fill';
    }
    if (
      value < currentRatingStar &&
      isFloat(value) &&
      Math.ceil(value) === currentRatingStar
    ) {
      return 'half-fill';
    }
    return 'line';
  };
</script>

<div class={componentClass} aria-disabled={disabled} {...$$restProps}>
  {#if !readonly}
    <div
      class="vtmn-rating--interactive"
      aria-label="Rate the article"
      role="radiogroup"
      data-rating={value}
    >
      {#each Array(starsCnt) as _, index}
        {@const position = index + 1}
        <input
          type="radio"
          bind:group={value}
          {name}
          value={position}
          id={`${name}-${position}`}
          aria-label={`${position} star out of 5`}
          {disabled}
        />
        <label for={`${name}-${position}`} />
      {/each}
    </div>
  {/if}
  {#if readonly}
    {#each Array(starsCnt) as _, index}
      {@const position = index + 1}
      <VtmnIcon
        value={`star-${computeRatingFill(position)}`}
        role="presentation"
      />
    {/each}
    {#if showValue}
      <span class="vtmn-rating_comment--primary" aria-label="article rating">
        {value}/5
      </span>
    {/if}
    {#if comments}
      <span
        class="vtmn-rating_comment--secondary"
        aria-label="number of ratings"
      >
        {comments}
      </span>
    {/if}
  {/if}
</div>

<style>
  @import '@vtmn/css-rating';
</style>

// packages/sources/vue/src/components/indicators/VtmnRating/VtmnRating.vue
<script lang="ts">
import VtmnIcon from '../../../guidelines/iconography/VtmnIcon';
import '@vtmn/css-rating/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnRatingSize } from './types';
import { computeRatingFill } from './utils';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnRating',
  components: { VtmnIcon },
  inheritAttrs: false,
  props: {
    name: {
      type: String as PropType<string>,
    },
    emphasis: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    size: {
      type: String as PropType<VtmnRatingSize>,
      default: 'medium',
      validator: (val: VtmnRatingSize) => ['small', 'medium'].includes(val),
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    readonly: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    compact: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    value: {
      type: Number as PropType<number>,
      default: 0,
    },
    showValue: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    comments: {
      type: Number as PropType<number>,
      default: undefined,
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      computeRatingFill,
      styleObject: {
        color: 'inherit',
        fontSize: 'none',
      },
      classes: computed(() => ({
        'vtmn-rating': true,
        [`vtmn-rating_size--${props.size}`]: props.size,
        'vtmn-rating_variant--brand': props.emphasis,
      })),
    };
  },
});
</script>

<template>
  <div :class="classes" :aria-disabled="disabled" v-bind="readonly && $attrs">
    <div
      v-if="!readonly"
      class="vtmn-rating--interactive"
      aria-label="Rate this"
      role="radiogroup"
      v-bind="$attrs"
    >
      <template v-for="i in 5" :key="i">
        <input
          type="radio"
          :group="value"
          :name="name"
          :value="i"
          :id="`${name}-${i}`"
          :aria-label="`${i} star out of 5`"
          :disabled="disabled"
        />
        <label :for="`${name}-${i}`" />
      </template>
    </div>
    <template v-else-if="!compact">
      <template v-for="i in 5" :key="i">
        <VtmnIcon
          :value="computeRatingFill(i, value)"
          :style="styleObject"
          role="presentation"
        />
      </template>
      <span
        v-if="showValue"
        class="vtmn-rating_comment--primary"
        aria-label="rate"
      >
        {{ value }}/5
      </span>
      <span
        v-if="comments"
        class="vtmn-rating_comment--secondary"
        aria-label="number of ratings"
      >
        {{ comments }}
      </span>
    </template>
    <template v-else>
      <VtmnIcon
        :value="
          value <= 2 ? 'star-line' : value < 4 ? 'star-half-fill' : 'star-fill'
        "
        :style="styleObject"
        role="presentation"
      />
    </template>
  </div>
</template>
