// packages/sources/react/src/components/VtmnCheckbox/VtmnCheckbox.tsx
import * as React from 'react';

import '@vtmn/css-checkbox';

export interface VtmnCheckboxProps
  extends React.ComponentPropsWithoutRef<'input'> {
  /**
   * ID of the checkbox.
   * @type {string}
   */
  identifier: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  labelText?: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  name?: string;

  /**
   * Label text linked to the checkbox.
   * @type {string}
   * @default null
   */
  value?: string;

  /**
   * Label text linked to the checkbox.
   * @type {boolean}
   * @default false
   */
  checked?: boolean;

  /**
   * Label text linked to the checkbox.
   * @type {boolean}
   * @default false
   */
  disabled?: boolean;
}

export const VtmnCheckbox = ({
  identifier,
  labelText,
  name,
  value,
  checked,
  disabled,
  ...props
}: VtmnCheckboxProps) => {
  return (
    <div>
      <input
        className="vtmn-checkbox"
        type="checkbox"
        id={identifier}
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        {...props}
      />
      <label htmlFor={identifier}>{labelText}</label>
    </div>
  );
};

export default React.memo(VtmnCheckbox);

// packages/sources/vue/src/components/VtmnCheckbox/VtmnCheckbox.vue
<script lang="ts">
import '@vtmn/css-checkbox/dist/index.css';
import { defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnCheckbox',
  props: {
    identifier: {
      type: String,
      default: null,
    },
    labelText: {
      type: String,
      default: null,
    },
    name: {
      type: String,
      default: null,
    },
    value: {
      type: String,
      default: null,
    },
    checked: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<template>
  <input
    class="vtmn-checkbox"
    type="checkbox"
    :id="this.identifier"
    :name="this.name"
    :value="this.value"
    :checked="this.checked"
    :disabled="this.disabled"
    v-bind="$attrs"
  />
  <label :for="this.identifier">{{ this.labelText }}</label>
</template>
