// packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import { VTMN_POPOVER_POSITION } from './enums';

  /**
   * ID of the popover
   * @type {string}
   */
  export let id;

  /** @type {'top' | 'bottom' | 'left' | 'right' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'} */
  export let position = VTMN_POPOVER_POSITION.TOP;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn('vtmn-popover', className);
</script>

<div
  class={componentClass}
  data-position={position}
  aria-describedby={id}
  aria-labelledby={`${id}-title`}
  tabindex="0"
  {...$$restProps}
>
  <slot />

  <div {id} role="dialog">
    <p class="vtmn-popover_title" id={`${id}-title`} role="heading">
      <slot name="title" />
    </p>
    <p class="vtmn-popover_text"><slot name="body" /></p>
  </div>
</div>

<style lang="css">
  @import '@vtmn/css-popover';
</style>

// packages/sources/vue/src/components/overlays/VtmnPopover/VtmnPopover.vue
<script lang="ts">
import '@vtmn/css-popover/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';
import { VtmnPopoverPosition } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnPopover',
  inheritAttrs: false,
  props: {
    id: {
      type: String as PropType<string>,
      required: true,
    },
    position: {
      type: String as PropType<VtmnPopoverPosition>,
      default: 'top',
      validator: (val: VtmnPopoverPosition) =>
        [
          'top-left',
          'top',
          'top-right',
          'right',
          'bottom-right',
          'bottom',
          'bottom-left',
          'left',
        ].includes(val),
    },
    title: {
      type: String as PropType<string>,
    },
    body: {
      type: String as PropType<string>,
    },
  },
});
</script>

<template>
  <div
    class="vtmn-popover"
    :data-position="position"
    :aria-describedby="id"
    :aria-labelledby="id + '-title'"
    tabindex="0"
    v-bind="$attrs"
  >
    <slot />

    <div :id="id" role="dialog">
      <p :id="id + '-title'" class="vtmn-popover_title" role="heading">
        {{ title }}
      </p>
      <p class="vtmn-popover_text">{{ body }}</p>
    </div>
  </div>
</template>
