// packages/sources/vue/src/components/overlays/VtmnModal/VtmnModal.vue
<script lang="ts">
import '@vtmn/css-modal/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import { VtmnButton } from '../../index';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnModal',
  components: { VtmnButton },
  inheritAttrs: false,
  props: {
    open: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  emits: ['close'],
  setup(props, { emit }) {
    props = reactive(props);

    const handleClose = () => {
      return emit('close');
    };

    return {
      classes: computed(() => ({
        'vtmn-modal': true,
      })),
      handleClose,
    };
  },
});
</script>

<template>
  <div
    v-if="open"
    :class="classes"
    role="dialog"
    aria-modal="true"
    v-bind="$attrs"
  >
    <div class="vtmn-modal_background-overlay" @click.prevent="handleClose" />
    <div class="vtmn-modal_content">
      <div class="vtmn-modal_content_title">
        <span v-if="$slots.title" class="vtmn-modal_content_title--text">
          <slot name="title" />
        </span>
        <VtmnButton
          aria-label="close"
          variant="ghost"
          size="medium"
          iconAlone="close-line"
          @click.prevent="handleClose"
        />
      </div>

      <div v-if="$slots.description" class="vtmn-modal_content_body">
        <slot name="description" />
      </div>

      <div v-if="$slots.actions" class="vtmn-modal_content_actions">
        <slot name="actions" />
      </div>
    </div>
  </div>
</template>

// packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
<script>
  import { cn } from '../../../utils/classnames';
  import VtmnButton from '../../actions/VtmnButton/VtmnButton.svelte';
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  /**
   * @type {boolean} Display or hide the modal
   * Default false
   */
  export let open = false;

  /**
   * @type {string} Id of the modal
   */
  export let id = undefined;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn('vtmn-modal_content', className);

  const handleClose = () => {
    dispatch('close', { open });
  };
</script>

<svelte:head>
  {#if open}
    <style type="text/css">
      body {
        overflow: hidden;
      }
    </style>
  {/if}
</svelte:head>

{#if open}
  <div
    class="vtmn-modal"
    role="dialog"
    aria-modal="true"
    aria-labelledby={$$restProps['aria-labelledby']}
    aria-describedby={$$restProps['aria-describedby']}
  >
    <div
      id="vtmn-modal-background"
      class="vtmn-modal_background-overlay"
      on:click={handleClose}
    />
    <div {id} class={componentClass}>
      <div class="vtmn-modal_content_title">
        {#if $$slots.title}
          <span id="vtmn-modal-title" class="vtmn-modal_content_title--text"
            ><slot name="title" /></span
          >
        {/if}
        <VtmnButton
          aria-label="close"
          variant="ghost"
          iconAlone="close-line"
          on:click={handleClose}
        />
      </div>
      <div class="vtmn-modal_content_body">
        {#if $$slots.description}
          <p id="vtmn-modal-description" class="vtmn-modal_content_body--text">
            <slot name="description" />
          </p>
        {/if}
      </div>
      {#if $$slots.actions}
        <div class="vtmn-modal_content_actions">
          <slot name="actions" />
        </div>
      {/if}
    </div>
  </div>
{/if}

<style>
  @import '@vtmn/css-modal';
</style>
