// packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdown.tsx
import * as React from 'react';
import '@vtmn/css-dropdown/dist/index-with-vars.css';

export interface VtmnDropdownProps
  extends React.ComponentPropsWithoutRef<'div'> {
  /**
   * The label of the dropdown.
   * @defaultValue undefined
   */
  label?: string;

  /**
   * The summary of the dropdown.
   * @defaultValue undefined
   */
  summary?: string;

  /**
   * Whether the dropdown is disabled.
   * @defaultValue undefined
   */
  disabled?: boolean;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnDropdown = ({
  label = 'Label',
  summary = 'Dropdown',
  disabled = false,
  className,
  children,
  ...props
}: VtmnDropdownProps) => {
  return (
    <div className="vtmn-dropdown" aria-disabled={disabled}>
      <label htmlFor={props['id']}>{label}</label>
      <details>
        <summary aria-labelledby={props['id']}>{summary}</summary>
        <div
          className="vtmn-dropdown_items"
          role="group"
          aria-labelledby={props['id']}
        >
          {children}
        </div>
      </details>
    </div>
  );
};

const MemoVtmnDropdown = React.memo(VtmnDropdown);

MemoVtmnDropdown.displayName = 'VtmnDropdown';

export default MemoVtmnDropdown;

// packages/sources/vue/src/components/actions/VtmnDropdown/VtmnDropdown.vue
<script lang="ts">
import '@vtmn/css-dropdown/dist/index-with-vars.css';
import { defineComponent, PropType } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnDropdown',
  props: {
    label: {
      type: String as PropType<string>,
      default: 'Label',
    },
    summary: {
      type: String as PropType<string>,
      default: 'Dropdown',
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(_, { attrs }) {
    const labelId = attrs['id'] ? String(attrs['id']) : undefined;

    return {
      labelId,
    };
  },
});
</script>

<template>
  <div class="vtmn-dropdown" :aria-disabled="disabled">
    <label :for="labelId">{{ label }}</label>
    <details>
      <summary :aria-labelledby="labelId">{{ summary }}</summary>
      <div
        className="vtmn-dropdown_items"
        role="group"
        :aria-labelledby="labelId"
      >
        <slot />
      </div>
    </details>
  </div>
</template>
