// packages/sources/vue/src/components/structure/VtmnAccordion/VtmnAccordion.vue
<script lang="ts">
import '@vtmn/css-accordion/dist/index-with-vars.css';
import { reactive, computed, defineComponent, PropType } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnAccordion',
  inheritAttrs: false,
  props: {
    summary: {
      type: String as PropType<string>,
    },
    withIconLeft: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    disabled: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    open: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
  },
  setup(props) {
    props = reactive(props);
    return {
      classes: computed(() => ({
        'vtmn-accordion': true,
        'vtmn-accordion--with-icon-left': props.withIconLeft,
      })),
    };
  },
});
</script>

<template>
  <details
    :class="classes"
    :aria-disabled="disabled"
    :open="open"
    :aria-expanded="open"
    v-bind="$attrs"
  >
    <summary>
      <slot name="summaryComponent" v-if="$slots.summaryComponent" />
      <template v-else>{{ summary }}</template>
    </summary>
    <div class="vtmn-accordion_content">
      <slot />
    </div>
  </details>
</template>

// packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
<script>
  import { cn } from '../../../utils/classnames';

  /**
   * @type {string} Summary of the accordion.
   * @requires
   */
  export let summary = undefined;

  /**
   * @type {boolean} Display left icon on summary.
   * @default false
   */
  export let withIconLeft = false;

  /**
   * @type {boolean} Disable the accordion.
   * @default false
   */
  export let disabled = false;

  /**
   * @type {boolean} Open the accordion.
   * @default false
   */
  export let open = false;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };
  $: componentClass = cn(
    'vtmn-accordion',
    withIconLeft && 'vtmn-accordion--with-icon-left',
    className,
  );
</script>

<details
  class={componentClass}
  aria-disabled={disabled}
  aria-expanded={open}
  {open}
  {...$$restProps}
>
  <summary>
    {#if $$slots.summaryComponent}
      <slot name="summaryComponent" />
    {:else}
      {summary}
    {/if}
  </summary>
  <div class="vtmn-accordion_content">
    <slot />
  </div>
</details>

<style lang="css">
  @import '@vtmn/css-accordion';
</style>
