// packages/sources/vue/src/components/navigation/VtmnTabs/VtmnTabs.vue
<script lang="ts">
import '@vtmn/css-tabs/dist/index-with-vars.css';
import { computed, defineComponent, PropType, reactive } from 'vue';
import VtmnDivider from '../../structure/VtmnDivider/VtmnDivider.vue';

import { VtmnTabsAlign, VtmnTabsSize } from './types';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnTabs',
  components: { VtmnDivider },
  props: {
    align: {
      type: String as PropType<VtmnTabsAlign>,
      default: 'start',
      validator: (val: VtmnTabsAlign) =>
        ['start', 'center', 'end'].includes(val),
    },
    size: {
      type: String as PropType<VtmnTabsSize>,
      default: 'medium',
      validator: (val: VtmnTabsSize) => ['small', 'medium'].includes(val),
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-tabs': true,
        [`vtmn-tabs_align--${props.align}`]: props.align,
        [`vtmn-tabs_size--${props.size}`]: props.size,
      })),
    };
  },
});
</script>

<template>
  <nav :class="classes" v-bind="$attrs">
    <ul role="tablist">
      <slot />
    </ul>
    <VtmnDivider />
  </nav>
</template>

// packages/sources/react/src/components/navigation/VtmnTabs/VtmnTabs.tsx
import * as React from 'react';
import '@vtmn/css-tabs/dist/index-with-vars.css';
import { VtmnTabsAlign, VtmnTabsSize } from './types';
import { VtmnDivider } from '../../../components/structure/VtmnDivider';
import clsx from 'clsx';

export interface VtmnTabsProps extends React.ComponentPropsWithoutRef<'ul'> {
  /**
   * The alignment of the tabs.
   * @type {VtmnTabsAlign}
   * @defaultValue 'start'
   */
  align?: VtmnTabsAlign;

  /**
   * The size of the tabs.
   * @type {VtmnTabsSize}
   * @defaultValue 'medium'
   */
  size?: VtmnTabsSize;

  /**
   * The content to render inside the component.
   * @defaultValue undefined
   */
  children?: React.ReactNode;
}

export const VtmnTabs = ({ className, children, ...props }: VtmnTabsProps) => {
  return (
    <nav>
      <ul
        className={clsx(
          'vtmn-tabs',
          `vtmn-tabs_align--${props.align}`,
          `vtmn-tabs_size--${props.size}`,
          className,
        )}
        role="tablist"
        {...props}
      >
        {children}
      </ul>
      <VtmnDivider />
    </nav>
  );
};

const MemoVtmnTabs = React.memo(VtmnTabs);

MemoVtmnTabs.displayName = 'VtmnTabs';

export default MemoVtmnTabs;
