// packages/sources/web-components/src/components/vtmn-toggle/vtmn-toggle.tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'vtmn-toggle',
  styleUrl: 'vtmn-toggle.pcss',
  shadow: true,
})
export class VtmnButton {
  /**
   * The checked state of the toggle.
   * @default false
   */
  @Prop() checked: boolean = false;

  /**
   * The disabled state of the toggle.
   * @default false
   */
  @Prop() disabled: boolean = false;

  /**
   * The size of the toggle.
   * @default 'medium'
   */
  @Prop() size: 'small' | 'medium' = 'medium';

  render() {
    return (
      <div class={'vtmn-toggle ' + `vtmn-toggle_size--${this.size}`}>
        <div class="vtmn-toggle_switch">
          <input
            type="checkbox"
            id="your-choice"
            checked={this.checked}
            disabled={this.disabled}
          />
          <span aria-hidden="true"></span>
        </div>
        <label htmlFor="your-choice">
          <slot></slot>
        </label>
      </div>
    );
  }
}

// packages/sources/svelte/src/components/selection-controls/VtmnToggle/VtmnToggle.svelte
<script>
  import { VTMN_TOGGLE_SIZE } from './enums';
  import { cn } from '../../../utils/classnames';

  /**
   * ID of the toggle and associated label
   * @type {string}
   * @requires
   */
  export let id;

  /**
   * @type {boolean} Define if the toggle is checked or not
   * @default false
   */
  export let checked = false;

  /**
   * @type {boolean} The disabled state of the toggle
   * @default false
   */
  export let disabled = false;

  /**
   * @type {'small'|'medium'} Size of the component
   * @default medium
   */
  export let size = VTMN_TOGGLE_SIZE.MEDIUM;

  let className = undefined;
  /**
   * @type {string} Custom classes to apply to the component.
   */
  export { className as class };

  $: componentClass = cn('vtmn-toggle', `vtmn-toggle_size--${size}`, className);
</script>

<div class={componentClass}>
  <div class="vtmn-toggle_switch">
    <input type="checkbox" {id} {disabled} bind:checked />
    <span aria-hidden="true" />
  </div>
  <label for={id}>
    <slot />
  </label>
</div>

<style lang="css">
  @import '@vtmn/css-toggle';
</style>
