// packages/sources/svelte/src/components/VtmnLink.svelte
<script>
  import '@vtmn/css-link';

  /**
   * The href of the link.
   * @type {string}
   * @default '#'
   */
  export let href = '#';

  /**
   * The target of the link.
   * @type {string}
   * @default '_self'
   */
  export let target = '_target';

  /**
   * The size of the link.
   * @type {string}
   * @default 'medium'
   */
  export let size = 'medium';

  /**
   * Whether link is standalone or not.
   * @type {boolean}
   * @default false
   */
  export let standalone = false;

  /**
   * Whether link has an icon or not.
   * @type {boolean}
   * @default false
   */
  export let iconAlong = false;
</script>

<a
  {href}
  {target}
  class={[
    'vtmn-link',
    `vtmn-link_size--${size}`,
    standalone && 'vtmn-link--standalone',
    standalone && iconAlong && 'vtmn-link--icon-along',
  ]
    .filter(Boolean)
    .join(' ')}
  {...$$props}
>
  <slot />
</a>

// packages/sources/vue/src/components/VtmnLink/VtmnLink.vue
<script lang="ts">
import '@vtmn/css-link/dist/index.css';
import { reactive, computed, defineComponent } from 'vue';

export default /*#__PURE__*/ defineComponent({
  name: 'VtmnLink',
  props: {
    href: {
      type: String,
      default: '#',
    },
    target: {
      type: String,
      default: '_self',
    },
    size: {
      type: String,
      default: 'medium',
      validator: (val: string) => ['small', 'medium', 'large'].includes(val),
    },
    standalone: {
      type: Boolean,
      default: false,
    },
    iconAlong: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    props = reactive(props);

    return {
      classes: computed(() => ({
        'vtmn-link': true,
        [`vtmn-link_size--${props.size}`]: true,
        'vtmn-link--standalone': props.standalone,
        'vtmn-link--icon-along': props.iconAlong && props.standalone,
      })),
    };
  },
});
</script>

<template>
  <a :href="href" :target="target" :class="classes" v-bind="$attrs">
    <slot></slot>
  </a>
</template>
